### ISSUE TITLE
Compile SDK 34 breaks tests including Dialog composable

### ISSUE THREAD

**Issue by dniHze** [cashapp/paparazzi#1057]
**Description**
When changing compile SDK to 34 (required for Compose 1.5.0 support afaik), tests including AlertDialog are failing to render when trying to create `DecorView`. It looks like bundled layoutlib just doesn't support resources format of `DecorView` which is present in SDK 34. 

**Steps to Reproduce**
1. Update tests to using Compose 1.5.0, set compile SDK to 34
2. Include `Dialog` composable into the test
3. Run record or verify
4. If the test includes only dialog composable - test fails with an exception
5. If the test includes other composables too - test fails silently and renders blank snapshots

Exceptions:

```
java.lang.NumberFormatException: Color value '/Users/artem.d/Library/Android/sdk/platforms/android-34/data/res/color/system_bar_background_semi_transparent.xml' has wrong size. Format is either#AARRGGBB, #RRGGBB, #RGB, or #ARGB
	at com.android.layoutlib.bridge.impl.ResourceHelper.getColor(ResourceHelper.java:136)
	at android.content.res.Resources_Delegate.getColor(Resources_Delegate.java:221)
	at android.content.res.Resources.getColor(Resources.java:1065)
	at com.android.internal.policy.DecorView.<init>(DecorView.java:313)
	at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2385)
	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2727)
	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2144)
	at androidx.compose.ui.window.DialogWrapper.<init>(AndroidDialog.android.kt:352)
	at androidx.compose.ui.window.AndroidDialog_androidKt.Dialog(AndroidDialog.android.kt:163)

--- OR --- 

android.content.res.Resources$NotFoundException: Could not find dimen resource matching value 0x105024F (resolved name: resize_shadow_size) in current configuration.
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1161)
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1137)
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1141)
	at app//android.content.res.Resources_Delegate.getDimensionPixelSize(Resources_Delegate.java:670)
	at app//android.content.res.Resources.getDimensionPixelSize(Resources.java:828)
	at app//com.android.internal.policy.DecorView.<init>(DecorView.java:320)
	at app//com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2385)
	at app//com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2727)
	at app//com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2144)
	at app//androidx.compose.ui.window.DialogWrapper.<init>(AndroidDialog.android.kt:352)
	at app//androidx.compose.ui.window.AndroidDialog_androidKt.Dialog(AndroidDialog.android.kt:163)
```

**Expected behavior**
Paparazzi renders respective tests correctly.

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: macOS Ventura 13.4
- Compile SDK: 34
- Gradle Version: 8.3
- Android Gradle Plugin Version: 8.1.1

**Comment by TWiStErRob** [comment]
Might be fixed by https://github.com/cashapp/paparazzi/pull/1050, give 1.3.2-SNAPSHOT a [try](https://github.com/cashapp/paparazzi#releases).

**Comment by dniHze** [comment]
Hey @TWiStErRob, thanks for your suggestion. Looks like the issue persists on the latest snapshot.

**Comment by sbilsky** [comment]
Workaround is here https://github.com/cashapp/paparazzi/issues/1025
But yeah waiting a fix as well.

**Comment by sbilsky** [comment]
This workaround works for me https://github.com/cashapp/paparazzi/issues/1025#issuecomment-1654065507
But it need some extra work on CI.

**Comment by dniHze** [comment]
It looks so that AS Hedgehog handles the rendering properly, whilst Giraffe is failing on rendering previews for such composable. I guess this would stick for a while until the next patch or Hedgehog release.

**Comment by dniHze** [comment]
Closing as duplicate of #1025
