### ISSUE TITLE
NPE when using SwitchCompat

### ISSUE THREAD

**Issue by bananita** [cashapp/paparazzi#1059]
**Description**
When creating snapshots with SwitchCompat, I get NPE. To reproduce it, I modified launch.xml from example project. I used Material Design 1.9.0.

How can I deal with `it?`

```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "source" is null
	at android.text.StaticLayout.<init>(StaticLayout.java:474)
	at androidx.appcompat.widget.SwitchCompat.makeLayout(SwitchCompat.java:995)
	at androidx.appcompat.widget.SwitchCompat.onMeasure(SwitchCompat.java:916)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:667)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.doLayout(RenderSessionImpl.java:418)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:564)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:461)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:314)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:313)
	at app.cash.paparazzi.Paparazzi.withTime(Paparazzi.kt:361)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:313)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:207)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:206)
	at app.cash.paparazzi.sample.LaunchViewTest.nexus5_differentOrientations(LaunchViewTest.kt:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:126)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Steps to Reproduce**
```

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:gravity="center"
    android:background="@color/launchBackground"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

  <ImageView
      android:layout_width="200dp"
      android:layout_height="200dp"
      android:src="@drawable/camera"
      />

  <TextView
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:gravity="center"
      android:textColor="@color/cameraBody"
      android:text="paparazzi"
      android:textSize="70dp"
      android:textFontWeight="100"
      />

  <androidx.appcompat.widget.SwitchCompat
    android:id="@+id/switchRememberCard"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content" />

</LinearLayout>
```

**Comment by oguzcelik** [comment]
I was facing the same issue and I kind of found a working solution. I'll need to test a bit more things but writing it now to share and get more opinions.

It's a cryptic error but it boils down to switch compat needing an appcompat theme for some attributes. If you are directly taking a screenshot of an android view you can try this
### Simple Workaround that does not affect the real implementation
```
val contextWithTheme = ContextThemeWrapper(
    context,
    R.style.Theme_AppCompat // any appcomat theme
)

val view = YourView(contextWithTheme)

paparazzi.snapshot(view)
```
### Another possible candidate that I couldn't figure out
Paparazzi class also has a constructor parameter for theme: 
```
private val theme: String = "android:Theme.Material.NoActionBar.Fullscreen",
```
But I couldn't make it work so far. Maybe I'm defining the theme wrong since it's a string I'm a bit confused there 😅 
### Issue I'm trying to solve
My problem is a bit different because I'm writing a test for a composable which has an AndroidView inside it. I'm sure I can figure out a way to do the same for my setup without affecting the code that goes to production, I'll share it if I do 👍 
### How I came to this conclusion
Previously we faced a similar issue in our isolated ui tests with espresso. If we call `setContent` on a `composeTestRule`, the test would crash when running on the emulator. We solved this by using  adding a manifest file to the `androidTest` source. It would look something like this: 
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application android:supportsRtl="true">

        <activity
            android:name="androidx.fragment.app.FragmentActivity"
            android:theme="@style/SomeAppcompatTheme" />
    </application>
</manifest>

// In your test, instead of an empty compose rule
createAndroidComposeRule<FragmentActivity>()
```

But our compose previews of the composables with android views was not working on android studio either. The tests would pass on the emulator though.

I'm considering adding the theme to the `AndroidView` like below but I don't like it because it's affecting the real implementation. This also fixes the compose previews on android studio.
```
 AndroidView(
        factory = { context ->
            val contextWithTheme = ContextThemeWrapper(
                context,
                R.style.Theme_AppCompat
            )

            MyAndroidview(contextWithTheme)
        },
```

Just wanted to share my discovery so far so that maybe someone can help find a more elegant solution 🚀  Let me know if you have one

**Comment by TWiStErRob** [comment]
Nice one! Re `theme` arg, I think you simply don't need the prefix and need to use something that extends appcompat: https://github.com/TWiStErRob/net.twisterrob.sun/blob/main/component/paparazzi/src/main/java/net/twisterrob/sun/test/screenshots/PaparazziFactory.kt#L11

Themes defined here: https://github.com/TWiStErRob/net.twisterrob.sun/blob/main/component/theme/src/main/res/values/themes.xml

**Comment by oguzcelik** [comment]
Thanks! That actually worked for my case. I put our app theme for the paparazzi setup as well 🚀 I'll check out if we need a different theme for screenshot tests or the real one is good enough 👍

**Comment by TWiStErRob** [comment]
@jrodbx would it make sense to auto-detect AndroidX, and if it's on the classpath (there's already code for this for some other reason afair), then use the base theme from it by default? Same for material maybe.

**Comment by bananita** [comment]
@oguzcelik, @TWiStErRob, thank you, guys!
workaround based on ContextThemeWrapper works like a charm.
