### ISSUE TITLE
Crashes thrown during measurement of composables do not bubble up

### ISSUE THREAD

**Issue by saket** [cashapp/paparazzi#1068]
**Description**
When errors are thrown during a composable's layout/measurement phase, they do not cause the test to fail. Instead, an empty screenshot is generated. Can paparazzi catch them instead of only logging them to `System.err`?

**Steps to Reproduce**

```kotlin
paparazzi.snapshot {
  LazyColumn {
    item("key") {}
    item("key") {}
  }
}
```

<details>
<summary>Stacktrace</summary>

```
SEVERE: broken: View measure failed
java.lang.IllegalArgumentException: Key "key" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:433)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:807)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:121)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure(LazyListMeasuredItemProvider.kt:48)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-50ZNEM8(LazyListMeasure.kt:181)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(LazyList.kt:322)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:187)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke-0kLqBqw(LazyLayout.kt:103)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:96)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:644)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
	…
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt:995)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:302)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:289)
	at android.view.View.measure_Original(View.java:26358)
	…
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:655)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.doLayout(RenderSessionImpl.java:408)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:551)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:451)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:314)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:313)
	at app.cash.paparazzi.Paparazzi.withTime(Paparazzi.kt:361)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:313)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:207)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:206)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:202)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:198)
```
</details>

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: macOS 13.5
- Compile SDK: 34
- Gradle Version: 8.2.0
- Android Gradle Plugin Version: 8.1.0

**Comment by TWiStErRob** [comment]
Did you mean "Can paparazzi ~catch~ throw them instead of only logging them to System.err?"?

**Comment by saket** [comment]
Oh whoops yeah. Let me fix that.

**Comment by geoff-powell** [comment]
This issue was fixed in 2.0.0-alpha04
https://github.com/cashapp/paparazzi/pull/2214
