### ISSUE TITLE
AlertDialog not working.

### ISSUE THREAD

**Issue by CharlesMoreira1** [cashapp/paparazzi#1086]
**Description**

I'm trying to test an AlertDialog with Material3 in Compose, and I'm receiving the following error:

```
android.content.res.Resources$NotFoundException: Could not find dimen resource matching value 0x105024F (resolved name: resize_shadow_size) in current configuration.
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1161)
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1137)
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1141)
	at app//android.content.res.Resources_Delegate.getDimensionPixelSize(Resources_Delegate.java:670)
	at app//android.content.res.Resources.getDimensionPixelSize(Resources.java:828)
	at app//com.android.internal.policy.DecorView.<init>(DecorView.java:320)
	at app//com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2385)
	at app//com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2727)
	at app//com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2144)
	at app//androidx.compose.ui.window.DialogWrapper.<init>(AndroidDialog.android.kt:352)
	at app//androidx.compose.ui.window.AndroidDialog_androidKt.Dialog(AndroidDialog.android.kt:163)
	at app//androidx.compose.material3.AndroidAlertDialog_androidKt.AlertDialog(AndroidAlertDialog.android.kt:151)
	at app//androidx.compose.material3.AndroidAlertDialog_androidKt.AlertDialog-Oix01E0(AndroidAlertDialog.android.kt:92)
	at app//com.lingshot.home_presentation.ui.component.HomePieChartCardKt.HomePierChartCard(HomePieChartCard.kt:99)
	at app//com.lingshot.home_presentation.ui.component.ComposableSingletons$HomePieChartCardSnapshotTestKt$lambda-1$1.invoke(HomePieChartCardSnapshotTest.kt:25)
	at app//com.lingshot.home_presentation.ui.component.ComposableSingletons$HomePieChartCardSnapshotTestKt$lambda-1$1.invoke(HomePieChartCardSnapshotTest.kt:24)
	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
```
```
class HomePieChartCardSnapshotTest {
    @get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = DeviceConfig.PIXEL_4A,
        renderingMode = SessionParams.RenderingMode.SHRINK
    )

    @Test
    fun homePieChart_Displayed_By_Default() {
        paparazzi.snapshot {
            LingshotTheme {
                HomePierChartCard(
                    goals = Pair(
                        UserLocalDomain(goal = 10),
                        GoalsDomain(progressPhrases = 5)
                    ),
                    isSetGoalsDialogVisible = true,
                    selectedGoalDays = 10,
                    listCountPhrases = HomeUiState().goalDaysList,
                    onSelectedGoalDays = {},
                    onSaveGoals = {},
                    onToggleSetGoalsDialog = {}
                )
            }
        }
    }
}
```
```
@Composable
internal fun HomePierChartCard(
    goals: Pair<UserLocalDomain?, GoalsDomain?>?,
    isSetGoalsDialogVisible: Boolean,
    selectedGoalDays: Int,
    listCountPhrases: ImmutableList<Int>,
    onSelectedGoalDays: (Int) -> Unit,
    onSaveGoals: (Int) -> Unit,
    onToggleSetGoalsDialog: () -> Unit,
    modifier: Modifier = Modifier
) {
    val newGoals = goals?.first?.goal ?: 0
    val completed = goals?.second?.progressPhrases ?: 0

    ElevatedCard {
        Row(
            modifier = modifier
                .fillMaxWidth()
                .padding(16.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            HomePieChart(
                modifier = Modifier.size(120.dp),
                goals = newGoals,
                completed = completed
            )
            Column {
                HomePieChartIndicator(
                    value = newGoals.toString(),
                    type = stringResource(R.string.text_label_piechart_goals_home),
                    color = LocalSchemeCustom.current.goalsPieChart
                )
                HomePieChartIndicator(
                    value = completed.toString(),
                    type = stringResource(R.string.text_label_piechart_completed_home),
                    color = LocalSchemeCustom.current.completedPieChart
                )
            }
            IconButton(
                onClick = onToggleSetGoalsDialog
            ) {
                Icon(imageVector = Icons.Default.Edit, contentDescription = null)
            }
        }
    }

    if (isSetGoalsDialogVisible) {
        AlertDialog(
            onDismissRequest = onToggleSetGoalsDialog,
            dismissButton = {
                TextButton(onClick = onToggleSetGoalsDialog) {
                    Text(text = stringResource(R.string.text_button_cancel_goals_dialog_home))
                }
            },
            confirmButton = {
                TextButton(onClick = {
                    onSaveGoals(selectedGoalDays)
                }) {
                    Text(text = stringResource(R.string.text_button_save_goal_dialog_home))
                }
            },
            title = {
                Text(
                    text = stringResource(R.string.text_title_goals_dialog_home),
                    fontSize = 18.sp
                )
            },
            text = {
                GoalsDropdownMenu(
                    selectedGoalDays = selectedGoalDays,
                    listCountPhrases = listCountPhrases,
                    onSelectedGoalDays = onSelectedGoalDays
                )
            }
        )
    }
}
```

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: macOs Ventura 13.3.1
- Compile SDK: 34
- Gradle Version: 8.1.1
- Android Gradle Plugin Version: 8.2

**Comment by TWiStErRob** [comment]
https://github.com/cashapp/paparazzi/issues/1025
