### ISSUE TITLE
RobolectricTestRunner/AndroidJunitTestRunner not supported if includeAndroidResources = true

### ISSUE THREAD

**Issue by sergio-sastre** [cashapp/paparazzi#1089]
**Description**
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)

This relates to this Issue:
https://github.com/cashapp/paparazzi/issues/425

**Steps to Reproduce**
1. Add Robolectric to gradle
`testImplementation "org.robolectric:robolectric:4.10.3"`
2. Add `includeAndroidResources = true` necessary for Robolectric, otherwise the test is skipped
```groovy
testOptions {
        unitTests {
            includeAndroidResources = true
        }
}
```

3. Add the RobolectricTestRunner or AndroidJunitTestRunner to your screenshot test
```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [33])
class CoffeeDrinkAppBarComposableHappyPathTest {
    @get:Rule
    val paparazzi =
        Paparazzi(
            deviceConfig =
            DeviceConfig.PIXEL_5.copy(
                nightMode = NightMode.NOTNIGHT,
                fontScale = 1.0f,
                locale = "en",
            ).setPhoneOrientation(PhoneOrientation.PORTRAIT),
            renderingMode = SessionParams.RenderingMode.V_SCROLL,
        )

    @Test
    fun snapComposable() {
        paparazzi.context.setDisplaySize(DisplaySize.LARGER)

        paparazzi.snapshot(name = "CoffeeDrinkAppBar_Happy") {
            AppTheme {
                CoffeeDrinkAppBar()
            }
        }
    }
}
```

**Expected behavior**
Tests should also run if `includeAndroidResources = true`

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: MacOS
- Compile SDK: 33
- Gradle Version: 8.x
- Android Gradle Plugin Version: 8.x

You can find a reproducible example in [this repo](https://github.com/sergio-sastre/Android-screenshot-testing-playground), branch `bug/robolectric+paparazzi`, :lazycolumnscreen:paparazzi module, test class  -["CoffeeDrinkAppBarComposableHappyPathTest"](https://github.com/sergio-sastre/Android-screenshot-testing-playground/blob/bug/robolectric%2Bpaparazzi/lazycolumnscreen/paparazzi/src/test/java/com/example/road/to/effective/snapshot/testing/lazycolumnscreen/paparazzi/CoffeeDrinkAppBarComposableTest.kt)

**Comment by agrosner** [comment]
we worked around that by adding this snippet to our common modules config (applied to all of them):
```groovy
testOptions {
        unitTests.all {
            // Remove when https://github.com/cashapp/paparazzi/issues/384 is fixed
            if (JavaVersion.current() >= JavaVersion.VERSION_13) {
                jvmArgs "-XX:+AllowRedefinitionToAddDeleteMethods"
            }
        }
    }
```

**Comment by jrodbx** [comment]
I'm confused; Paparazzi tests are not intended to be used with @RunWith(RobolectricTestRunner::class).

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [33])
class CoffeeDrinkAppBarComposableHappyPathTest {
    @get:Rule
    val paparazzi =
        Paparazzi(
            deviceConfig = ...
            renderingMode = SessionParams.RenderingMode.V_SCROLL,
        )
```

What's the use case for combining these two in the same test class/suite?

**Comment by sergio-sastre** [comment]
Since Robolectric supports Activity and FragmentScenarios as well as ComposeRules, you could use their APIs in the Paparazzi tests e.g. for taking screenshots of Activities (not saying that is a good practice, but it is sometimes convenient)

**Comment by jrodbx** [comment]
> Sorry for the confusion!

No worries!  Appreciate the additional context.  Hmm, I wonder then if this issue is more theoretical than an actual bug.

Paparazzi is very opinionated about:
1) running on a JVM only (vs a device).
2) taking screenshots only of views and Composables (not Activities and fragments, since those are only hosts, and have nothing to do with rendering).

Those opinions make it so that adding `@RunWith(RobolectricTestRunner::class)` on a test suite/class that is intended to interact with Paparazzi is considered user error.  If your view or Composable has references to an Activity or Services, architect/refactor them so that they do not!

I do, however, want to ensure that co-mingling test classes in a test source set does work, i.e., it should be perfectly fine to have in `src/test`, TestA that uses `@RunWith(RobolectricTestRunner::class)` (a Robolectric test), and TestB that has `@get:Rule val paparazzi = ` (a Paparazzi test).

**Comment by sergio-sastre** [comment]
> > Sorry for the confusion!
> 
> No worries! Appreciate the additional context. Hmm, I wonder then if this issue is more theoretical than an actual bug.
> 
> Paparazzi is very opinionated about:
> 
> 1. running on a JVM only (vs a device).
> 2. taking screenshots only of views and Composables (not Activities and fragments, since those are only hosts, and have nothing to do with rendering).
> 
> Those opinions make it so that adding `@RunWith(RobolectricTestRunner::class)` on a test suite/class that is intended to interact with Paparazzi is considered user error. If your view or Composable has references to an Activity or Services, architect/refactor them so that they do not!
> 
> I do, however, want to ensure that co-mingling test classes in a test source set does work, i.e., it should be perfectly fine to have in `src/test`, TestA that uses `@RunWith(RobolectricTestRunner::class)` (a Robolectric test), and TestB that has `@get:Rule val paparazzi = ` (a Paparazzi test).
> 
> Maybe, another (more realistic) example is what would help here?

The actual use case is to screenshot a full recyclerView hosted by an Activity.

Sometimes is very inconvenient having to set all the recyclerview adapters instead of just inflating the Activity and screenshot testing it.

However I understand this is just a “very special use case”, so feel free to close this.

I can confirm that if you have Paparazzi tests without RobolectricTestRunner, they work, regardless of whether Robolectric is used in the module.

thanks for your time!

**Comment by TWiStErRob** [comment]
I think if you extract the onCreate/setupView method from the activity into a separate class, you'll be able to drive it from Paparazzi with ease. It's not as easy/black-box as "just" launching an activity, but it should at least work.

**Comment by sampengilly** [comment]
It seems that simply adding the paparazzi gradle plugin to a project which uses Robolectric/AndroidJUnit4 in tests causes them to fail. They throw these exceptions without even including the Paparazzi test rule in the test class:

```
'org.hamcrest.Matcher org.hamcrest.core.AllOf.allOf(org.hamcrest.Matcher, org.hamcrest.Matcher)'
java.lang.NoSuchMethodError: 'org.hamcrest.Matcher org.hamcrest.core.AllOf.allOf(org.hamcrest.Matcher, org.hamcrest.Matcher)'
	at org.hamcrest.Matchers.allOf(Matchers.java:33)
	at androidx.test.espresso.Espresso.<clinit>(Espresso.java:5)
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:316)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:271)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:589)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
Could not initialize class androidx.test.espresso.Espresso
java.lang.NoClassDefFoundError: Could not initialize class androidx.test.espresso.Espresso
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:316)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:271)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:589)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

In terms of use cases, I'm using robolectric to run simple compose functionality tests (e.g. confirming that a composable has the correct semantics tree). I'd like to also add Paparazzi alongside for capturing the visuals. Ideally it should be possible to use both the ComposeTestRule and the Paparazzi test rule independently in the same class.

**Comment by TWiStErRob** [comment]
re
> Ideally it should be possible to use both the ComposeTestRule and the Paparazzi test rule independently in the same class.

@sampengilly sadly the JUnit RunWith/Rule are nested if they're applied in the same class, see the `run`/`evaluate` calls in the stack. So using Robolectric and Paparazzi both of which mess with the classloader in some way, will cause a conflict. Also (in general) doing class-level setup not used by every test is discouraged because of the random unnecessary interplay they can cause.

You could try using [`Enclosed`](https://stackoverflow.com/a/15158587/253468) to have them "in the same class", but probably better off with fully separate `FooBarUnitTests`, `FooBarPaparazziTests` and `FooBarRobolectricTests` classes. I agree that having to use separate modules for them is a bit overkill, but likely necessary right now, @jrodbx?

**Comment by sampengilly** [comment]
If they have to be in separate classes due to an underlying conflict like that then that's also ok. But as it stands it seems that you can't even include Paparazzi (by applying the plugin) in a project that uses Robolectric to run Compose tests

**Comment by sampengilly** [comment]
Would it be possible to set up a separate test configuration and source directory in a single Gradle module, so that paparazzi can sit alongside the built-in `test` dir?

**Comment by TWiStErRob** [comment]
As far as I know Gradle-wise it's possible (see e.g. test suites) to set up a sourceSet with different dependencies (i.e. runtime classpath), but we're in AGP world so having one global `android.testOptions.unitTests.includeAndroidResources` (and similar AGP things) could be a blocker.

**Comment by jrodbx** [comment]
@sergio-sastre can you check and see if this is now fixed on latest per https://github.com/cashapp/paparazzi/pull/1167?

**Comment by sergio-sastre** [comment]
> @sergio-sastre can you check and see if this is now fixed on latest per #1167?

Very Gladly!
I’ll try to find time this week. Otherwise it will have to wait till January, but I promise to check if it works 🙏

**Comment by jrodbx** [comment]
@sampengilly can you confirm if your issue still occurs?  if so, could you please file another issue?  this issue is geared towards the OP's repro, and they may or may not be related.

**Comment by jrodbx** [comment]
@sergio-sastre bumping the sample you provided (thanks!) to `app.cash.paparazzi.gradle.plugin-1.3.2-20231209.235200-98` now results in an issue, similar to https://github.com/cashapp/paparazzi/issues/988.

**Comment by jrodbx** [comment]
Update:
* as mentioned [here](https://github.com/cashapp/paparazzi/issues/1089#issuecomment-1848575878), we've updated our interceptors' usage of Bytebuddy to be a little more respectful of working in the same module with Robolectric.
* from there, I applied [this workaround Gradle snippet](https://github.com/cashapp/paparazzi/blob/master/sample/guava-fix.gradle) to handle the issue [introduced by the latest version of Truth/Guava](https://github.com/cashapp/paparazzi/pull/1214).
* I still get an issue with:
```
> Task :lazycolumnscreen:paparazzi:testDebugUnitTest FAILED
JNIHelp F 01-13 13:20:36 17223 21345896] java.lang.NoSuchMethodError: Method 'java.lang.String android.os.SystemProperties.native_get(java.lang.String, java.lang.String)' is not declared as native
JNIHelp F 01-13 13:20:36 17223 21345896] RegisterNatives failed for 'android/os/SystemProperties'; aborting...
```
which indicates that RobolectricTestRunner is interfering with Paparazzi's ability to load Bridge.init which in turns sets up SystemProperties for things like BuildConfig.

Removing:
```
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [33])
```
allows the test to pass as expected:

![image](https://github.com/cashapp/paparazzi/assets/1868149/a3a065b5-f306-44b3-95d2-9be860999c2e).

Note that all other tests (including Robolectric tests!) run fine, with the above recipe, per the following command:
```
./gradlew lazycolumnscreen:paparazzi:testDebug
```

Therefore, I'm considering the original issue as closed.  Paparazzi appears to now play nicely alongside Robolectric tests, which is an improvement from before!  To go even further, (i.e., allowing Paparazzi AND RobolectricTestRunner to be in the same test) is out of scope.  I'd love to support it, but I'm doubtful as to whether that will bear fruit given that the two frameworks both mock bits of the Android platform and so there is bound to be conflicts.

That being said, I'm happy to accept PRs or continue the discussion if other contributors/maintainers have ideas/PRs.

**Comment by sampengilly** [comment]
Apologies for returning to this a month later, it looks like there might still be issues with the tests operating side by side.

I have applied the Paparazzi Plugin to my project again, I created a separate test class to hold the paparazzi screenshot tests so I have one test class for Robolectric tests and one plain JUnit class that doesn't use the Robolectric/Android test runner. 

Running the standard unit test task or paparazzi record task causes a bunch of errors for NoClassDefFound around the EspressoLink.android class, one or two for hamcrest matchers (which I see another issue for with a workaround, we don't use hamcrest in our project, so it is only a transitive dependency), and one or two other classes.

```
java.lang.NoClassDefFoundError: Could not initialize class androidx.test.espresso.Espresso
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:320)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:271)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:588)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
