### ISSUE TITLE
java.lang.NoSuchMethodError: int android.graphics.Color.rgb(int, int, int)

### ISSUE THREAD

**Issue by CharlesMSilva** [cashapp/paparazzi#1090]
**Description**

I'm trying to implement Paparazzi in the company's app, and I'm encountering the following error:

```
java.lang.NoSuchMethodError: 'int android.graphics.Color.rgb(int, int, int)'
	at android.view.View.<clinit>(View.java:2356)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at app.cash.paparazzi.Paparazzi.registerViewEditModeInterception(Paparazzi.kt:574)
	at app.cash.paparazzi.Paparazzi.apply(Paparazzi.kt:136)
	at org.junit.runners.RuleContainer.apply(RuleContainer.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:412)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:321)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

```
class AwarenessActionTipsSnapshotTest {

    @get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = DeviceConfig.PIXEL_4A
    )

    @Test
    fun awarenessActionTips_Displayed_By_Default() {
        val launch = paparazzi.inflate<ConstraintLayout>(
            R.layout.wallet_home_awareness_action_tips
        )

        paparazzi.snapshot(launch)
    }
}
```

**Expected behavior**

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: macOS Ventura 13.3.1
- Compile SDK: 33
- Gradle Version: 7.2.2
- Android Gradle Plugin Version: 7.4

**Comment by TWiStErRob** [comment]
Try to downgrade to [1.2.0](https://github.com/cashapp/paparazzi/blob/master/CHANGELOG.md#120---2023-01-18), Paparazzi versions newer than that probably need AGP 8.x.

Alternatively upgrade your tooling to 8.1.1.

**Comment by TWiStErRob** [comment]
How did you solve it? (In case someone runs into the same.)

**Comment by CharlesMSilva** [comment]
> How did you solve it? (In case someone runs into the same.)

So, I couldn't solve it. But I found out that it was some issue with the project's roboelectric and a plugin from my company.

But to solve it, I created a module called `testsnapshot` and imported the module's features into it. This way, I isolated the tests and removed the dependency on roboelectric and the company's plugin.
