### ISSUE TITLE
UnsupportedOperationException when running tests with isTestCoverageEnabled

### ISSUE THREAD

**Issue by nesfeder** [cashapp/paparazzi#1121]
**Description**
When trying to run a unit test with Paparazzi (or any of the included gradle tasks), I'm seeing this crash:
```
class redefinition failed: attempted to delete a method
java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1032)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1162)
	at net.bytebuddy.dynamic.loading.$Proxy38.retransformClasses(Unknown Source)
	at net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Strategy$2.apply(ClassReloadingStrategy.java:399)
	at net.bytebuddy.dynamic.loading.ClassReloadingStrategy.load(ClassReloadingStrategy.java:227)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6317)
	at app.cash.paparazzi.agent.InterceptorRegistrar$addMethodInterceptors$1.invoke(InterceptorRegistrar.kt:34)
	at app.cash.paparazzi.agent.InterceptorRegistrar$addMethodInterceptors$1.invoke(InterceptorRegistrar.kt:22)
	at app.cash.paparazzi.agent.InterceptorRegistrar.registerMethodInterceptors(InterceptorRegistrar.kt:39)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:15)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
```

**Steps to Reproduce**
[Sample project](https://github.com/nesfeder/paparazzi-repro-app)
- Running unit test (`ExampleUnitTest`) will reproduce the exception. 
- Similar to #1089, https://github.com/cashapp/paparazzi/issues/1089#issuecomment-1721304528 will stop the exception from being thrown.

I confirmed with the test project that commenting out `isTestCoverageEnabled = true` fixes the issue and tests pass successfully.

**Expected behavior**
Tests are successfully setup and pass.

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: macOS Ventura 13.6
- Compile SDK: 33
- Gradle Version: 8.0
- Android Gradle Plugin Version: 8.1.1

**Comment by nesfeder** [comment]
@jrodbx feel free to close this if you feel it's a dupe of https://github.com/cashapp/paparazzi/issues/955

**Comment by u7452206** [comment]
Hi, if anyone work on this issue? If not, I would like to help.

**Comment by jrodbx** [comment]
@nesfeder can you check latest and see if https://github.com/cashapp/paparazzi/pull/1167 fixes this issue as well?

**Comment by matejdro** [comment]
`app.cash.paparazzi.gradle.plugin-1.3.2-20231209.235200-98` fixes the issue for me.

**Comment by jrodbx** [comment]
Confirmed as fixed, using the provided sample project (thanks for that!  yay for sample projects!)
