### ISSUE TITLE
Flaky `NoSuchElementException` when running 

### ISSUE THREAD

**Issue by nhaarman** [cashapp/paparazzi#1128]
**Description**
When running `./gradlew recordPaparazzi` or `./gradlew verifyPaparazzi`, _sometimes_ a test fails with the stack trace below. A re-run of the command usually fixes the issue.

**Steps to Reproduce**
N/A

**Expected behavior**
N/A

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: MacOS 14.0
- Compile SDK: 33
- Gradle Version: 8.3
- Android Gradle Plugin Version: 7.3.0

**Screenshots**

```
java.util.NoSuchElementException
	at java.base/java.util.LinkedList.getFirst(LinkedList.java:248)
	at com.android.layoutlib.bridge.util.HandlerMessageQueue.lambda$extractFirst$1(HandlerMessageQueue.java:75)
	at java.base/java.util.WeakHashMap.forEach(WeakHashMap.java:1026)
	at com.android.layoutlib.bridge.util.HandlerMessageQueue.extractFirst(HandlerMessageQueue.java:73)
	at android.os.Handler_Delegate.executeCallbacks(Handler_Delegate.java:95)
	at app.cash.paparazzi.Paparazzi.executeHandlerCallbacks(Paparazzi.kt:575)
	at app.cash.paparazzi.Paparazzi.forceReleaseComposeReferenceLeaks(Paparazzi.kt:565)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:320)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:200)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:199)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:195)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:191)
	at nohrd.connections.navigation.DashboardViewSnapshotTest.viewTest(DashboardViewSnapshotTest.kt:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:118)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:429)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

Our tests look like this:

```
@RunWith(TestParameterInjector::class)
class WorkoutDetailsViewSnapshotTest(
    @TestParameter val darkTheme: Boolean,
    @TestParameter snapshotDevice: SnapshotDevice,
) {

    @get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = snapshotDevice.deviceConfig,
        renderingMode = SessionParams.RenderingMode.V_SCROLL,
        showSystemUi = false,
    )

    @Test
    fun test() {
        paparazzi.snapshot {
            Box(modifier = Modifier.heightIn(max = 2000.dp)) {
                WorkoutDetailsViewPreview(darkTheme = darkTheme)
            }
        }
    }
}
```

```
enum class SnapshotDevice(
    val deviceConfig: DeviceConfig,
) {

    PIXEL_6_PRO(deviceConfig = DeviceConfig.PIXEL_6_PRO),
    NEXUS_5_LAND(deviceConfig = DeviceConfig.NEXUS_5_LAND),
}
```

**Comment by jrodbx** [comment]
Have you tried on 1.3.1?

**Comment by nhaarman** [comment]
We are now, and haven't seen issues so far. I'll reopen this issue if I see it happening again!
