### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: 'long android.os.Trace.nativeGetEnabledTags()'

### ISSUE THREAD

**Issue by MedetZhakupov** [cashapp/paparazzi#1149]
**Description**
We use molecule library in our project. And unitests for Composable presenter functions we have are failing when adding paparazzi as dependency. The stacktrace is:

```
Exception in thread "Test worker @coroutine#2" kotlinx.coroutines.CompletionHandlerException: Exception in completion handler InvokeOnCompletion@26723525[job@80b70fd] for "coroutine#4":StandaloneCoroutine{Cancelled}@80b70fd
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1502)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:325)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:242)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:910)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:832)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:169)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at app.cash.molecule.MoleculeKt$immediateClockFlow$1$1.invokeSuspend(molecule.kt:63)
	at app.cash.molecule.MoleculeKt$immediateClockFlow$1$1.invoke(molecule.kt)
	at app.cash.molecule.MoleculeKt$immediateClockFlow$1$1.invoke(molecule.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at app.cash.molecule.MoleculeKt$immediateClockFlow$1.invokeSuspend(molecule.kt:59)
	at app.cash.molecule.MoleculeKt$immediateClockFlow$1.invoke(molecule.kt)
	at app.cash.molecule.MoleculeKt$immediateClockFlow$1.invoke(molecule.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.cash.turbine.FlowTurbineKt$test$2$collectJob$1.invokeSuspend(FlowTurbine.kt:309)
	at app.cash.turbine.FlowTurbineKt$test$2$collectJob$1.invoke(FlowTurbine.kt)
	at app.cash.turbine.FlowTurbineKt$test$2$collectJob$1.invoke(FlowTurbine.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at app.cash.turbine.FlowTurbineKt$test$2.invokeSuspend(FlowTurbine.kt:58)
	at app.cash.turbine.FlowTurbineKt$test$2.invoke(FlowTurbine.kt)
	at app.cash.turbine.FlowTurbineKt$test$2.invoke(FlowTurbine.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at app.cash.turbine.FlowTurbineKt.test-dWUq8MI(FlowTurbine.kt:55)
	at app.cash.turbine.FlowTurbineKt.test-dWUq8MI$default(FlowTurbine.kt:51)
	at com.privatebanking.feature.buysellopinion.ui.details.DetailsPresenterTest$test opinion details successful load$1.invokeSuspend(DetailsPresenterTest.kt:40)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.privatebanking.feature.buysellopinion.ui.details.DetailsPresenterTest.test opinion details successful load(DetailsPresenterTest.kt:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [app.cash.molecule.GatedFrameClock@28effa3f, CoroutineId(4), "coroutine#4":StandaloneCoroutine{Cancelled}@80b70fd, Dispatchers.Unconfined]
Caused by: java.lang.UnsatisfiedLinkError: 'long android.os.Trace.nativeGetEnabledTags()'
	at android.os.Trace.nativeGetEnabledTags(Native Method)
	at android.os.Trace.isTagEnabled(Trace.java:163)
	at android.os.Trace.beginSection(Trace.java:382)
	at androidx.compose.runtime.Trace.beginSection(ActualAndroid.android.kt:31)
	at androidx.compose.runtime.ComposerImpl.dispose$runtime_release(Composer.kt:4573)
	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:631)
	at app.cash.molecule.MoleculeKt$launchMolecule$2$2.invoke(molecule.kt:159)
	at app.cash.molecule.MoleculeKt$launchMolecule$2$2.invoke(molecule.kt:158)
	at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1385)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1497)
	... 89 more

Expected item but found Error(UnsatisfiedLinkError)
app.cash.turbine.AssertionError: Expected item but found Error(UnsatisfiedLinkError)
```

**Steps to Reproduce**
```kotlin
@Test
fun `test functions`() = runBlocking {
            moleculeFlow(mode = RecompositionMode.Immediate) {
                        flowOf("Text")
                    }.test {
                        assertEquals(
                            "Text",
                            expectItem()
                        )
                    }
}
```
**Expected behavior**
Expectation is to unit test not to fail when adding paparazzi as dependency

**Additional information:**
- Paparazzi Version: 1.3.1
- OS:
- Compile SDK: 33
- Gradle Version: 8.1.1
- Android Gradle Plugin Version: 8.0.2

**Screenshots**

**Comment by MedetZhakupov** [comment]
I have checkout out other similar issues here and noticed that if I put paparazzi rule inside unit test class, as shown below, tests pass as normal.
```kotlin
@get:Rule
    val paparazzi = Paparazzi(
        renderingMode = SessionParams.RenderingMode.SHRINK,
        showSystemUi = false
    )
```

**Comment by epool** [comment]
I'm facing exactly the same issue, but I'm only using plain JUnit + Mockito in my unit tests. Adding the Paparazzi test rule fixed it also. Maybe the Paparazzi gradle plugging is doing/missing something under the hood?

**Comment by jrodbx** [comment]
@epool @MedetZhakupov can one of you provide a repro sample?

**Comment by jrodbx** [comment]
@epool @MedetZhakupov a repro sample would help get eyes on this.

**Comment by tordjon** [comment]
@jrodbx 
https://github.com/tordjon/moleculepaparazzirepro

app.cash.turbine.TurbineAssertionError: Expected item but found Error(UnsatisfiedLinkError)
...
	at app.cash.turbine.FlowKt$collectIntoChannel$job$1.invokeSuspend(flow.kt:228)
Caused by: java.lang.UnsatisfiedLinkError: 'long android.os.Trace.nativeGetEnabledTags()'
	at android.os.Trace.nativeGetEnabledTags(Native Method)
	at android.os.Trace.isTagEnabled(Trace.java:163)

Hopefully you'll have a change to look at it, let me know if you need anything else

```buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.4.0'
//        classpath 'app.cash.paparazzi:paparazzi-gradle-plugin:1.3.3' <------
    }
}

plugins {
    id 'com.android.application'
    id 'kotlin-android'
//    id 'app.cash.paparazzi' version '1.3.3'.   <-------
}

Adding back these two lines the test will fail, commenting them out, the test wil pass

**Comment by geoff-powell** [comment]
hmm, looking at your repro project it seems like adding

```
    @get:Rule
    val paparazzi = Paparazzi()
    ```
    
   Fixes the issue, so there is something layoutlib does that messes up `long android.os.Trace.nativeGetEnabledTags()` call

**Comment by jrodbx** [comment]
### Investigation

`com.android.tools.layoutlib:layoutlib` (previously, `app.cash.paparazzi:layoutlib-native-jdk11`) is added to the classpath at test build time and provides a "mocked" version of the Android platform which allows test authors to resolve platform types, such as `android.view.View`, `android.app.Activity`, `android.os.Trace`, etc at compile time **and** classload them during test process runtime.

`android.os.Trace`'s implementation depends on native code.  In some cases, Layoutlib can choose to delegate these code paths to a custom method annotated with `@LayoutlibDelegate`.

However, in this case, Layoutlib chooses [not to do so, via KEEP_CLASSES_NATIVE](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/layoutlib/create/src/com/android/tools/layoutlib/create/CreateInfo.java;l=259?q=android.os.Trace&ss=android%2Fplatform%2Fsuperproject%2Fmain:frameworks%2Flayoutlib%2F).  Inevitably, this means the **native** code will need to be loaded via JNI to work properly.  

In LayoutLib, that **native** code bootstrap is accomplished at runtime via [Bridge.init](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/layoutlib/bridge/src/com/android/layoutlib/bridge/Bridge.java;l=194?q=Bridge.init&ss=android%2Fplatform%2Fsuperproject%2Fmain:frameworks%2Flayoutlib%2F) when loading the path denoted by the `core_native_classes` System property, which [refers to a list that contains](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/layoutlib/common/src/com/android/tools/layoutlib/create/NativeConfig.java;l=174?q=android.os.Trace&ss=android%2Fplatform%2Fsuperproject%2Fmain:frameworks%2Flayoutlib%2F) `android.os.Trace` as an element.

In Paparazzi, we call Bridge.init() as part of the Paparazzi Rule setup, via:

```
@get:Rule val paparazzi = Paparazzi()
```

which is why adding that in https://github.com/cashapp/paparazzi/issues/1149#issuecomment-2269640148 worked.

### Conclusion

This means:

* without layoutlib on the classpath, nor Bridge.init invoked
  * You cannot reference Android types at compile-time nor classload them at runtime.
  * This is a typical unit test classpath setup.
* with layoutlib on the classpath, but Bridge.init not invoked
  * You can reference Android types at compile-time AND classload them at runtime.
  * But any native dependencies that have not been delegated/proxied will require the JNI libraries to be loaded prior to invoking the corresponding native methods.
  * This is a typical case where you are running a non-Paparazzi test in the same process as a Paparazzi test, since the classpath will be shared.
* with layoutlib on the classpath AND Bridge.init invoked
  * This is a typical Paparazzi test run

### Potential solutions

* Load JNI libraries earlier, as part of the initial test process runtime
  * Custom Junit runner?  - Big con, runners do not compose well.  Would make interaction with TestParameterInjector, et al. trickier.
  * Custom class loader?  - The likely path, this could also likely isolate Paparazzi's world w.r.t. test runs from Robolectric, Mockito, etc.
  * Custom Java agent?  - similar to runner, classloader?  Not sure.  Never have written one, but sounds like it would avoid the runner composition issue and be easier than a custom class loader?  We know we want a custom class loader anyway for other reasons (R.jar on-the-fly), but is this the same hammer for a different nail type of problem?
* Separate test source set
  * I mention this only because Google's screenshot feature currently does this and it is "a solution", but I'm still kinda opposed to it as segregating tests by category makes employing test frameworks more challenging.  For example, the Junit reporting implementation was rewritten in Google's case(!) to support custom test reporting output.
* Convince the Google Layoutlib team to provide delegate classes/methods for android.os.Trace and potentially other types currently listed in KEEP_CLASS_NATIVES
  * This would be ideal for LayoutLib extensions (e.g., us), although I'm uncertain whether this intentionally designed to allow test assertions for tracing code.  I'll file an issue for this.

### Current path

I'd like to start with the Google issue and if they decide to keep as is, explore either the class loader or agent approach.  For now, punting this issue to the next milestone.

**Comment by jrodbx** [comment]
Forgot to mention: there is a workaround for this.  Organize your Paparazzi tests in a separate package/folder and use a test filter (i.e., `gw module:vPD --tests=com.yourcompany.paparazzi.*`) to achieve the test isolation outlined in the previous comment.

**Comment by jrodbx** [comment]
As I'm writing this issue, I'm questioning whether this might be a case of developer error.  In other words, is the underlying issue simply having `android.os.Trace` (or any Android platform type) in the presenter all?

The OP mentions using Molecule, which leverages the Compose runtime.  Therefore, the framework provides `@Composable` and its associated type.  Yet, having Layoutlib on the classpath for other reasons (i.e., Paparazzi tests) is what allows the type to resolve in the IDE.

Now, say you were dedicating this module to only presenter tests and therefore did not include Paparazzi/Layoutlib on the classpath.  The reference to `android.os.Trace` would now fail to resolve as a signal not to reference Android types, unless you also have Robolectric or some other mocked form of android.jar to resolve/compile/classload `android.os.Trace`.

Anyway, I've filed the [Google issue here](https://issuetracker.google.com/issues/375395107#comment2), because if they're on board with the proposal, that'd make this point moot.

Thoughts?

**Comment by jrodbx** [comment]
Relevant commit: https://android.googlesource.com/platform/frameworks/layoutlib/+/ef874add645d04b87e91f3046a048b69c41106bd

[Looks like](https://github.com/cashapp/paparazzi/compare/2.0.0-alpha01...HEAD) `2.0.0-alpha01` had 15.1.4 per [this commit](https://github.com/cashapp/paparazzi/commit/6220dcf607c2120b231e33c946158132c53aa891).

Downloading all jars from 15.1.4 to 15.2.3 (current) from [Google's maven](https://maven.google.com/web/index.html?q=layoutl#com.android.tools.layoutlib:layoutlib:15.1.4) and checking for the presence of `android/os/Trace_Delegate` (per the filed Google issue) reveals:

```
$ for jar in $(find . -name "*.jar"); do
  if jar tf "$jar" | grep -q 'android/os/Trace_Delegate.class'; then
    echo "Found in $jar"
  else
    echo "Not found in $jar"
  fi
done

Found in ./layoutlib-15.2.3.jar
Not found in ./layoutlib-15.2.2.jar
Not found in ./layoutlib-15.2.0.jar
Not found in ./layoutlib-15.2.1.jar
Not found in ./layoutlib-15.1.4.jar
```

LayoutLib 15.2.3 [landed in 2.0.0-alpha02](https://github.com/cashapp/paparazzi/commit/473e3faffe838ad8217e6101d909f2d048ff78b2).

So, this has been fixed!

**Comment by arekolek** [comment]
I'm using paparazzi `2.0.0-alpha02`, wiremock `3.0.1` and okhttp `5.1.0` and I have a similar problem:

```kotlin
package com.example

import android.os.Trace
import com.github.tomakehurst.wiremock.junit.WireMockRule
import okhttp3.OkHttpClient
import org.junit.Rule
import org.junit.Test

class FooTest {
    @get:Rule
    val wireMockRule: WireMockRule = WireMockRule()

    @Test
    fun fails() {
        OkHttpClient.Builder().build()
    }

    @Test
    fun passes() {
        Trace.beginSection("test")
    }
}
```

`fails` test throws an exception:

```
'boolean android.util.Log.isLoggable(java.lang.String, int)'
java.lang.UnsatisfiedLinkError: 'boolean android.util.Log.isLoggable(java.lang.String, int)'
	at android.util.Log.isLoggable(Native Method)
	at okhttp3.internal.platform.android.AndroidLog.enableLogging(AndroidLog.kt:127)
	at okhttp3.internal.platform.android.AndroidLog.enable(AndroidLog.kt:109)
	at okhttp3.internal.platform.PlatformRegistry.findPlatform(PlatformRegistry.kt:25)
	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:223)
	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:202)
	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:203)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:300)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1384)
	at com.example.FooTest.fails(FooTest.kt:15)
```

Should I report a separate issue for this, or can this one be re-opened?
