### ISSUE TITLE
Mixing with Roboelectric causes errors 

### ISSUE THREAD

**Issue by burntcookie90** [cashapp/paparazzi#1201]
**Description**
A project with paparazzi and roboelectric will not be able to run tests. They all fail with the following:

```
java.lang.NoSuchMethodError: 'org.hamcrest.Matcher org.hamcrest.core.AllOf.allOf(org.hamcrest.Matcher, org.hamcrest.Matcher)'
	at org.hamcrest.Matchers.allOf(Matchers.java:33)
	at androidx.test.espresso.Espresso.<clinit>(Espresso.java:5)
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:316)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:271)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:588)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Steps to Reproduce**
[sample](https://github.com/burntcookie90/paparazzi-roboelectric-error-repro)

run `recordPaparazzi`

**Expected behavior**
Should not error

Another instance: https://github.com/cashapp/paparazzi/issues/1089#issuecomment-1747784908

Creating new issue based on: https://github.com/cashapp/paparazzi/issues/1089#issuecomment-1854606319

**Comment by gamepro65** [comment]
Looks like you are running into https://github.com/cashapp/paparazzi/issues/622#issuecomment-1551872561

**Comment by burntcookie90** [comment]
Thanks! I'll apply the workaround tomorrow and verify it works. I'll close the issue then.

**Comment by burntcookie90** [comment]
verified

**Comment by jrodbx** [comment]
Cross-posting from https://github.com/cashapp/paparazzi/issues/622#issuecomment-1880172997

**Comment by jrodbx** [comment]
Cross-posting from https://github.com/cashapp/paparazzi/issues/622#issuecomment-1901814600
