### ISSUE TITLE
Test Paparazzi with Android R

### ISSUE THREAD

**Issue by jrodbx** [cashapp/paparazzi#124]
Tests broke when I ran locally, due to `detectEnvironment` picking up the android-R platform and not being able to classload `android.graphics.Typeface`.

```
$ ./gradlew paparazzi:test --tests=app.cash.paparazzi.PaparazziTest

> Task :paparazzi:test

app.cash.paparazzi.PaparazziTest > drawCalls FAILED
    java.lang.NullPointerException
        at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:199)
        at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:140)
        at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:138)
        at app.cash.paparazzi.PaparazziTest.drawCalls(PaparazziTest.kt:44)

app.cash.paparazzi.PaparazziTest > animationEvents FAILED
    java.lang.NullPointerException
        at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:199)
        at app.cash.paparazzi.Paparazzi.gif(Paparazzi.kt:158)
        at app.cash.paparazzi.Paparazzi.gif$default(Paparazzi.kt:150)
        at app.cash.paparazzi.PaparazziTest.animationEvents(PaparazziTest.kt:78)
```

**Comment by omainegra** [comment]
I'm facing a similar error when running on **CircleCI** (official docker images, i.e `circleci/android:api-29`), but it works in other images (i.e `mingc/android-build-box`). Are there any special requirements besides JDK 11 and Android 29 than I'm missing?

```
java.lang.NoClassDefFoundError: Could not initialize class android.graphics.Typeface
	at android.graphics.Paint_Delegate.reset(Paint_Delegate.java:1262)
	at android.graphics.Paint_Delegate.<init>(Paint_Delegate.java:1216)
	at android.graphics.Paint_Delegate.nInit(Paint_Delegate.java:689)
	at android.graphics.Paint.nInit(Paint.java)
	at android.graphics.Paint.<init>(Paint.java:558)
	at android.text.TextPaint.<init>(TextPaint.java:54)
	at android.widget.TextView.<init>(TextView.java:986)
	at android.widget.Button.<init>(Button.java:166)
	at android.widget.Button.<init>(Button.java:141)
	at androidx.appcompat.widget.AppCompatButton.<init>(AppCompatButton.java:74)
	at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:198)
	at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:194)
        ...
```

**Comment by menny** [comment]
I see this, too. Any suggestions on what to do?

**Comment by omainegra** [comment]
It's hard to say, just tried the `openjdk:11` official docker image and it worked 🤷‍♂️

**Comment by omainegra** [comment]
I narrowed it to `openjdk:11-jdk-slim` docker image, which according to Docker doc

>This image installs the -headless package of OpenJDK and so is missing many of the UI-related Java libraries and some common packages contained in the default tag. It only contains the minimal packages needed to run Java. Unless you are working in an environment where only the openjdk image will be deployed and you have space constraints, we highly recommend using the default image of this repository.

**Comment by madisp** [comment]
regarding api 30, would upgrading `layoutlib` here help? Newer version of Android Studio can work with the `android-30` platforms so there must be some changes there.

**Comment by AbdelrahmanTalat** [comment]
> regarding api 30, would upgrading `layoutlib` here help? Newer version of Android Studio can work with the `android-30` platforms so there must be some changes there.

Hi @madisp any luck using api 30?
