### ISSUE TITLE
Crash when using M3 Dynamic colors

### ISSUE THREAD

**Issue by sergio-sastre** [cashapp/paparazzi#1359]
**Description**
After migrating from M2 to M3 and using dynamic colors, the task to execute screenshot tests fails as follows:
```
android.content.res.Resources$NotFoundException: Could not resolve resource value: 0x1060060.
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1159)
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1135)
	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1139)
	at app//android.content.res.Resources_Delegate.getColorStateList(Resources_Delegate.java:268)
	at app//android.content.res.Resources_Delegate.getColor(Resources_Delegate.java:246)
	at app//android.content.res.Resources.getColor(Resources.java:1065)
	at app//androidx.compose.material3.ColorResourceHelper.getColor-WaAFU9c(DynamicTonalPalette.android.kt:205)
	at app//androidx.compose.material3.DynamicTonalPaletteKt.dynamicLightColorScheme34(DynamicTonalPalette.android.kt:307)
	at app//androidx.compose.material3.DynamicTonalPaletteKt.dynamicLightColorScheme(DynamicTonalPalette.android.kt:170)

```

**Steps to Reproduce**
In a project with M3, enable dynamic colors in the AppTheme e.g.
```kotlin
@SuppressWarnings
@Composable
fun AppTheme(
    content: @Composable () -> Unit
) {
    val inDarkMode: Boolean = isSystemInDarkTheme()

    val colors = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        val context = LocalContext.current
        if (inDarkMode) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
    } else {
        if (inDarkMode) darkThemeColors else lightThemeColors
    }

    MaterialTheme(
        colorScheme = colors,
        content = content
    )
}
```

Then execute the Paparazzi tests and see them crashing with the aforementioned error

**Expected behavior**
The tests should not crash. Actually the workaround is to configure the Paparazzi rule with compileSDKVersion 33 or lower. The following makes the tests pass:

```kotlin
environment = 
   detectEnvironment().copy(
      compileSdkVersion = 33,
   ),
```

**Additional information:**
- Paparazzi Version: 1.3.3
- OS:
- Compile SDK: 34
- Gradle Version:
- Android Gradle Plugin Version: 8.2.2

**Comment by TWiStErRob** [comment]
This looks very similar:
https://github.com/cashapp/paparazzi/issues/1025#issuecomment-1654065507

Is it possible #1314 will fix this?

**Comment by jrodbx** [comment]
@sergio-sastre per @TWiStErRob 's comment, is this now fixed with 1.3.4?

**Comment by jrodbx** [comment]
@sergio-sastre any updates?

**Comment by sergio-sastre** [comment]
> @sergio-sastre any updates?

Sorry, I’ve been sick all week long. I’ll test it once I get time, fortunately next week

**Comment by sergio-sastre** [comment]
> @sergio-sastre any updates?

I've finally got time to test it and it works with 1.3.4.
Thanks for your work! :)
