### ISSUE TITLE
Paparazzi 1.3.5-SNAPSHOT breaks Bouncycastle class loading

### ISSUE THREAD

**Issue by cbruegg** [cashapp/paparazzi#1617]
**Description**
Paparazzi 1.3.5-SNAPSHOT contains a [fix](https://github.com/cashapp/paparazzi/commit/c9a5b2ef5f9b74689400ed36a9a6a49032e43dfe) for font loading. It hotpatches a class to achieve this.

Unfortunately, there's an issue: The following line apparently causes it to instrument _all_ classes, which breaks the signature of Bouncycastle classes:

```kotlin
override fun isInstrumentable(classData: ClassData): Boolean = true
```

We are seeing test failures in unrelated Robolectric tests with the following error:

```
Could not initialize class org.bouncycastle.jcajce.provider.asymmetric.compositesignatures.CompositeSignaturesConstants
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.jcajce.provider.asymmetric.compositesignatures.CompositeSignaturesConstants
...
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.SecurityException: SHA-256 digest error for org/bouncycastle/jcajce/provider/asymmetric/compositesignatures/CompositeSignaturesConstants$CompositeName.class [in thread "SDK 34 Main Thread"]
```

**Suggested Fix**

I've applied the following change in a bugfix fork of Paparazzi and it seems to work:

```kotlin
override fun isInstrumentable(classData: ClassData): Boolean =
  classData.className == ResourcesCompatTransform.RESOURCES_COMPAT_CLASS_NAME.replace('/', '.')
```

Even though there's a check in `visitMethod` already for this class, it seems like even instrumenting Bouncycastle without making any actual changes to the bytecode breaks its signature.

**Steps to Reproduce**
- Create a Robolectric test in a module that also contains Paparazzi tests
- Make sure the Paparazzi tests run before the Robolectric tests
- Observe errors like `java.lang.SecurityException at ManifestEntryVerifier.java:256` with the root cause explained above

**Expected behavior**
Paparazzi should only instrument the `ResourcesCompat` class.

**Additional information:**
- Paparazzi Version: 1.3.5-SNAPSHOT from Oct 2, 2024
- OS: Linux
- Compile SDK: 34
- Gradle Version: 8.7
- Android Gradle Plugin Version: 8.6.0

**Comment by jrodbx** [comment]
Admittedly, I'm no ASM expert but I'm having a bit of trouble verifying this claim:

> The following line apparently causes it to instrument all classes, which breaks the signature of Bouncycastle classes

Accordingly to the docs for [isInstrumentable](https://developer.android.com/reference/tools/gradle-api/7.1/com/android/build/api/instrumentation/AsmClassVisitorFactory#isinstrumentable):

"If returned true, [createClassVisitor](https://developer.android.com/reference/tools/gradle-api/7.1/com/android/build/api/instrumentation/AsmClassVisitorFactory#createClassVisitor(com.android.build.api.instrumentation.ClassContext,%20org.objectweb.asm.ClassVisitor)) will be called and the returned class visitor will visit the class."

The way I interpret is that we return a `ResourcesCompatTransform` for every encountered class (which might be a bit of GC churn, but let's sidestep that concern for a moment), then it checks whether the visited class is the one we actually care about (`RESOURCES_COMPAT_CLASS_NAME`) and if so, swaps the specific call from `startsWith` to `contains`.  No bytecode is actually being rewritten as far as I can tell, so I'm inclined to think this isn't a Paparazzi issue.  Can you provide a minimal sample project that demonstrates the issue?

**Comment by jrodbx** [comment]
I'm not an ASM expert, but one possible cause might be:

```
      testInstrumentation.setAsmFramesComputationMode(
        FramesComputationMode.COMPUTE_FRAMES_FOR_INSTRUMENTED_METHODS
      )
```

**Comment by cbruegg** [comment]
I'm not an ASM expert either, so pardon me for any misunderstanding 😇 

I've attached a sample project containing a Paparazzi (1.3.5-SNAPSHOT) and Robolectric test. The Paparazzi test passes, while the Robolectric test fails with this Exception:

```
java.lang.ExceptionInInitializerError
	at org.bouncycastle.jcajce.provider.asymmetric.CompositeSignatures$Mappings.configure(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadServiceClass(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:203)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:283)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.SecurityException: SHA-256 digest error for org/bouncycastle/jcajce/provider/asymmetric/compositesignatures/CompositeSignaturesConstants$CompositeName.class
	at java.base/sun.security.util.ManifestEntryVerifier.verify(Unknown Source)
	at java.base/java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.base/java.util.jar.JarVerifier.update(Unknown Source)
	at java.base/java.util.jar.JarVerifier$VerifierStream.read(Unknown Source)
	at java.base/jdk.internal.loader.Resource.getBytes(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getBytes(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.compositesignatures.CompositeSignaturesConstants.<clinit>(Unknown Source)
	... 16 more
```

Changing the Paparazzi version in `app/build.gradle.kts` from `1.3.5-SNAPSHOT` to `1.3.4` makes both tests pass. A local fork of Paparazzi `1.3.5-SNAPSHOT` with the fix suggested in my first post also lets both tests pass. From my understanding, the change I'm suggesting prevents instrumenting classes that the font loading fix doesn't care about anyway.

[PaparazziBouncycastle.zip](https://github.com/user-attachments/files/17290770/PaparazziBouncycastle.zip)

**Comment by geoff-powell** [comment]
Thanks for providing the repro test project. Was able to find the issue on my end and putting up a PR now!
