### ISSUE TITLE
Could not load font in multi module project on Windows (since 1.3.5)

### ISSUE THREAD

**Issue by tim-ebner-exxeta** [cashapp/paparazzi#1701]
**Description**
Trying to use a custom font resource added in a second module on Windows with Paparazzi version 1.3.5 leads to following error:
```
java.lang.IllegalStateException: Could not load font
	at androidx.compose.ui.text.font.TypefaceRequestCache.runCached(FontFamilyResolver.kt:207)
	at androidx.compose.ui.text.font.FontFamilyResolverImpl.resolve(FontFamilyResolver.kt:92)
....
Caused by: java.lang.IllegalStateException: Unable to load font ResourceFont(resId=2131296256, weight=FontWeight(weight=400), style=Normal, loadingStrategy=Blocking)
	at androidx.compose.ui.text.font.FontListFontFamilyTypefaceAdapterKt.firstImmediatelyAvailable(FontListFontFamilyTypefaceAdapter.kt:193)
	at androidx.compose.ui.text.font.FontListFontFamilyTypefaceAdapterKt.access$firstImmediatelyAvailable(FontListFontFamilyTypefaceAdapter.kt:1)
...
Caused by: android.content.res.Resources$NotFoundException: Font resource ID #0x7f090000 could not be retrieved.
	at app//androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:572)
	at app//androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:413)
...
```

The error only appears on Windows. With Linux it works.
It also worked with version 1.3.3 and 1.3.4 on Windows

**Steps to Reproduce**
On you Windows Machine:
- Create a new Android project with Paparazzi 1.3.5
- Add a second module with a custom Font with Typography file where font is used
- Import he second module in your first module and use the typography
- Run Paparazzi test in first module

Minimal Example:
[MinimalExample.zip](https://github.com/user-attachments/files/17817731/MinimalExample.zip)

**Expected behavior**
I don't get an error when using a custom font.

**Additional information:**
- Paparazzi Version: **1.3.5**
- OS: **Windows**
- Compile SDK:  35
- Gradle Version: 8.0
- Android Gradle Plugin Version: 8.7.2

Thanks & Best Regards
Tim

**Comment by geoff-powell** [comment]
Verified issue is occuring on Mac OS as well. 

Thanks for reporting!

**Comment by geoff-powell** [comment]
Looks like the file path that is failing is something like this

`Paparazzi/app/../typography/build/intermediates/packaged_res/debug/packageDebugResources/font/acme.xml`

I have a hunch that `../` might be the culprit. Still investigating

**Comment by tim-ebner-exxeta** [comment]
Thanks @geoff-powell  for the fast response and taking care.

Sorry I've accidentally added the server font. If you add an locally provided font you'll get this errors as well.
For me it only occurred on Windows (with the locally provided font).

Do you need another example with a local provided font?

**Comment by birgitlexa** [comment]
I am experiencing this issue as well. My current workaround is to copy the custom local fonts into the module with the screenshot tests.

**Comment by EthanXu91** [comment]
this issue still exists in version 1.3.5 on windows 11 but not on Mac, suffering the same problem that can not load font in muti module, detail logs as below
`  Mar 17, 2025 1:53:01 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: broken: View measure failed
    java.lang.IllegalStateException: Could not load font
        at androidx.compose.ui.text.font.TypefaceRequestCache.runCached(FontFamilyResolver.kt:207)
        at androidx.compose.ui.text.font.FontFamilyResolverImpl.resolve(FontFamilyResolver.kt:92)
        at androidx.compose.ui.text.font.FontFamilyResolverImpl.resolve-DPcqOEQ(FontFamilyResolver.kt:79)
        at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics$resolveTypeface$1.invoke-DPcqOEQ(AndroidParagraphIntrinsics.android.kt:91)
        at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics$resolveTypeface$1.invoke(AndroidParagraphIntrinsics.android.kt:89)
        at androidx.compose.ui.text.platform.extensions.TextPaintExtensions_androidKt.applySpanStyle(TextPaintExtensions.android.kt:63)
        at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics.<init>(AndroidParagraphIntrinsics.android.kt:108)
        at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics_androidKt.ActualParagraphIntrinsics(AndroidParagraphIntrinsics.android.kt:183)
        at androidx.compose.ui.text.ParagraphIntrinsicsKt.ParagraphIntrinsics(ParagraphIntrinsics.kt:98)
        at androidx.compose.ui.text.ParagraphIntrinsicsKt.ParagraphIntrinsics$default(ParagraphIntrinsics.kt:91)
        a`

**Comment by Boonapart228** [comment]
@birgitlexa thx for help
