### ISSUE TITLE
PreviewView from CameraX no longer works when used in snapshot

### ISSUE THREAD

**Issue by geoff-powell** [cashapp/paparazzi#1739]
**Description**
Using `PreviewView` from camerax library fails to work correctly. Stacktrace as follows: 

```
java.lang.NoSuchMethodError: 'void android.hardware.display.DisplayManagerGlobal.
registerDisplayListener(android.hardware.display.DisplayManager$DisplayListener, android.os.
Handler, long, java.lang.String)'
at android.hardware.display.DisplayManager.registerDisplayListener(DisplayManager.java:/86)
at android.hardware.display.DisplayManager.registerDisplayListener(DisplayManager.java:763)
at androidx.camera.view.PreviewView.startListeningToDisplayChange(PreviewView.java:1102)
at androidx.camera.view.PreviewView.onAttachedToWindow(PreviewView.java:356)
...
```

It also seems to have the same error when referencing it in compose preview in AS.

![Image](https://github.com/user-attachments/assets/d395a2e7-dca2-4574-9853-7df875567c8d)

**Steps to Reproduce**
* Snapshot `PreviewView` with Paparazzi ([Branch](https://github.com/cashapp/paparazzi/compare/master...gpowell/previewview-repro))

**Expected behavior**

**Additional information:**
- Paparazzi Version: 2.0.0-SNAPSHOT
- OS: MAC OS X 
- Compile SDK: 34
- Gradle Version: 8.11
- Android Gradle Plugin Version: 8.7.3

**Comment by geoff-powell** [comment]
In layoutlib version 15.x.x the added an mocked implementation of DisplayManager. Now that `getDisplayManager()` does not return `null` the error in `PreviewView` happens with `registerDisplayListener`

**Comment by geoff-powell** [comment]
Looks like layoutlib `15.0.7+` fixes this issue

**Comment by geoff-powell** [comment]
Closing as 15.0.7+ fixes issue
