### ISSUE TITLE
Unable to add snapshot tests for views that depend on Android animation

### ISSUE THREAD

**Issue by yvonnewong** [cashapp/paparazzi#193]
Sample error message when running a snapshot test on AmountView:

```
java.lang.RuntimeException: Method setTimeListener in android.animation.TimeAnimator not mocked. See http://g.co/androidstudio/not-mocked for details.
at android.animation.TimeAnimator.setTimeListener(TimeAnimator.java)
at com.squareup.cash.ui.widget.amount.AnimationContext.<init>(AnimationTools.kt:19)
at com.squareup.cash.ui.widget.amount.AmountView.<init>(AmountView.kt:42)
at com.squareup.cash.ui.widget.amount.AmountView.<init>(AmountView.kt:31)
at com.squareup.cash.bitcoin.views.BitcoinPaymentPadView.<init>(BitcoinPaymentPadView.kt:26)
```

**Comment by jrodbx** [comment]
Taking a look at the exception message ("See http://g.co/androidstudio/not-mocked for details.") points to the solution, i.e., pasting the following snippet in the build.gradle of your Gradle module.

```
android {
  testOptions {
    unitTests.returnDefaultValues = true
  }
}
```
