### ISSUE TITLE
Paparazzi fails on CircleCI

### ISSUE THREAD

**Issue by madisp** [cashapp/paparazzi#217]
We're trying to use Paparazzi as part of our CI build & PR checks but it fails on CircleCI for some reason. I reproduced the issue by forking the repo and running the sample in CircleCI: https://app.circleci.com/pipelines/github/madisp/paparazzi/2/workflows/d62a07b5-8333-45e9-b249-410995ba9bc6/jobs/2/artifacts

It looks like some part of `Typeface` class initialization fails.

I tried to reproduce locally but had no success, is this somehow related to the environment like maybe CircleCI is running in headless or it's broken because of docker?

Stacktrace:

```
    java.lang.NoClassDefFoundError: Could not initialize class android.graphics.Typeface
        at android.graphics.Paint_Delegate.reset(Paint_Delegate.java:1262)
        at android.graphics.Paint_Delegate.<init>(Paint_Delegate.java:1216)
        at android.graphics.Paint_Delegate.nInit(Paint_Delegate.java:689)
        at android.graphics.Paint.nInit(Paint.java)
        at android.graphics.Paint.<init>(Paint.java:558)
        at android.graphics.drawable.ColorDrawable.<init>(ColorDrawable.java:56)
        at com.android.layoutlib.bridge.impl.ResourceHelper.getDrawable(ResourceHelper.java:318)
        at android.content.res.BridgeTypedArray.getDrawable(BridgeTypedArray.java:673)
        at android.view.View.<init>(View.java:5254)
        at android.view.ViewGroup.<init>(ViewGroup.java:675)
        at android.widget.FrameLayout.<init>(FrameLayout.java:99)
        at com.android.layoutlib.bridge.MockView.<init>(MockView.java:55)
        at com.android.layoutlib.bridge.MockView.<init>(MockView.java:51)
        at com.android.layoutlib.bridge.MockView.<init>(MockView.java:47)
        at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:324)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:501)
        at android.view.BridgeInflater.inflate(BridgeInflater.java:383)
        at app.cash.paparazzi.Paparazzi.inflate(Paparazzi.kt:153)
        at app.cash.paparazzi.sample.LaunchViewTest.pixel3_differentThemes(LaunchViewTest.kt:38)
```

Stdout & stderr are empty.

**Comment by madisp** [comment]
I ran `sudo apt-get install fontconfig` before running tests, seems to have fixed it. Closing issue as this has to do more with CircleCI than paparazzi.

**Comment by jrodbx** [comment]
Possibly related to this: https://github.com/cashapp/paparazzi/issues/124

I have also seen this issue locally when running on API 30+, due to the fonts directory no longer being present in `$ANDROID_SDK/platforms/API/data`.

```
$ ls $ANDROID_HOME/platforms/android-29/data
NOTICE.txt            annotations.zip       broadcast_actions.txt features.txt          layoutlib.jar         service_actions.txt   widgets.txt
activity_actions.txt  api-versions.xml      categories.txt        fonts                 res                   tzdata

$ ls $ANDROID_HOME/platforms/android-30/data
NOTICE.txt            activity_actions.txt  annotations.zip       api-versions.xml      broadcast_actions.txt categories.txt        features.txt          res                   service_actions.txt   widgets.txt
```

Workaround is to run all Paparazzi tests pinned to API 29 for now: https://github.com/cashapp/paparazzi/blob/master/.github/workflows/build.yml#L24

**Comment by madisp** [comment]
it's not directly related, just the failure mode is similar - the case in #124 prints the line to `stderr` that `data/fonts` is missing. Not having `fontconfig` in an ubuntu session silently fails, regardless of the API version. Both failures happen at `Typeface` class load.
