### ISSUE TITLE
Compose support

### ISSUE THREAD

**Issue by benkay** [cashapp/paparazzi#225]
I took a stab at getting a ComposeView working with Paparazzi. It doesn't work with 0.7.0, but I managed to get it working on the native layoutlib branch with a bit of hackery. I think most of this is solved by using native/newer layoutlib, but It'd be great if there was a built-in `paparazzi.snapshot(content: @Composable () -> Unit)` at some point

- Compose calls ViewTreeLifecycleOwner/ViewTreeSavedStateRegistryOwner.get(rootView). A workaround for now is to wrap the ComposeView in a FrameLayout which sets these on the root view in onAttachedToWindow
- I had to provide mocked versions of AutofillManager and ClipboardManager as the 4.1.0 layoutlib doesn't provide them from BridgeContext, and Compose looks them both up when initialising. It looks like the latest prebuilt from mirror-goog-studio-master-dev does, but I can't get past an unsatisfiedlinkerror when trying to use it. Pre-releases of studio aren't tagged, so I have no idea whether the 4.2.0 version has support for these or not..

**Comment by timrijckaert** [comment]
Hello @jrodbx I saw you committed https://github.com/cashapp/paparazzi/commit/e71a024d823cafa0cd2dc91765e8840d6ab3af67

Does that work for you?
I'm getting 

```
java.lang.ExceptionInInitializerError
	at android.view.autofill.AutofillManager.<clinit>(AutofillManager.java:252)
	at com.android.layoutlib.bridge.android.BridgeContext.<init>(BridgeContext.java:265)
	at com.android.layoutlib.bridge.impl.RenderAction.init(RenderAction.java:143)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.init(RenderSessionImpl.java:186)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:146)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:106)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at android.os._Original_Build.<clinit>(Build.java:227)
	... 42 more
```

**Comment by int02h** [comment]
I'm having the same crash as @timrijckaert but without Compose, just on regular Views.

**Comment by int02h** [comment]
@timrijckaert were you able to solve your issue?

**Comment by timrijckaert** [comment]
No I was hoping @jrodbx would reply 😅

**Comment by jrodbx** [comment]
@timrijckaert apologies, but WIP branches aren't ready for support ;)

On the CashApp team, we're using the commit you referenced internally and it seems to be working fine.  If i had to guess, maybe your compileSdk is 31 which Paparazzi/Layoutlib doesn't yet support as of https://github.com/cashapp/paparazzi/issues/264.

**Comment by timrijckaert** [comment]
I'm following up this lib closely and anxiously waiting for the Compose support.  

Keep up the good work!
