### ISSUE TITLE
Support webp images

### ISSUE THREAD

**Issue by RainNapper** [cashapp/paparazzi#258]
Webp drawable resources are showing up in screenshots broken images (see attached image).

After converting them to .png, they show up as expected, which leads me to believe it's an issue with .webp support.

![Screen Shot 2021-09-09 at 1 58 29 PM](https://user-images.githubusercontent.com/1449656/132761810-ffa05e7d-94c2-4b85-9db5-4c9d211375e1.png)

**Comment by a-smirnov-at-veriff** [comment]
@consp1racy I'm facing the same issue. If I add the library you've mentioned above, test fails:

```
java.lang.NoClassDefFoundError: Could not initialize class com.luciad.imageio.webp.WebPDecoderOptions
	at com.luciad.imageio.webp.WebPReadParam.<init>(WebPReadParam.java:24)
	at com.luciad.imageio.webp.WebPReader.getDefaultReadParam(WebPReader.java:147)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1464)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363)
	at android.graphics.Bitmap_Delegate.createBitmap(Bitmap_Delegate.java:124)
	at android.graphics.Bitmap_Delegate.createBitmap(Bitmap_Delegate.java:108)
	at com.android.layoutlib.bridge.impl.ResourceHelper.getDrawable(ResourceHelper.java:387)
	at android.content.res.Resources_Delegate.getDrawable(Resources_Delegate.java:186)
	at android.content.res.Resources.getDrawable(Resources.java:845)
	at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:104)
```
