### ISSUE TITLE
Test Paparazzi with Android S

### ISSUE THREAD

**Issue by jrodbx** [cashapp/paparazzi#264]
Tests broke when I ran locally, setting the testConfig in `paparazzi/build.gradle` to point to API 31.

```
$ ./gradlew paparazzi:test --tests=app.cash.paparazzi.PaparazziTest

> Task :paparazzi:test

app.cash.paparazzi.PaparazziTest > throwsRenderingExceptions FAILED
    java.lang.ExceptionInInitializerError
        at android.view.autofill.AutofillManager.<clinit>(AutofillManager.java:239)
        at com.android.layoutlib.bridge.android.BridgeContext.<init>(BridgeContext.java:256)
        at com.android.layoutlib.bridge.impl.RenderAction.init(RenderAction.java:133)
        at com.android.layoutlib.bridge.impl.RenderSessionImpl.init(RenderSessionImpl.java:180)
        at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:139)
        ...

        Caused by:
        java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
            at android.os._Original_Build.<clinit>(Build.java:214)
            ... 42 more

app.cash.paparazzi.PaparazziTest > drawCalls FAILED
    java.lang.NullPointerException
        at com.android.layoutlib.bridge.impl.Layout$Builder.findAppCompatActionBar(Layout.java:455)
        at com.android.layoutlib.bridge.impl.Layout$Builder.<init>(Layout.java:422)
        at com.android.layoutlib.bridge.impl.RenderSessionImpl.init(RenderSessionImpl.java:193)
        at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:139)
        ...

app.cash.paparazzi.PaparazziTest > animationEvents FAILED
    java.lang.NullPointerException
        at com.android.layoutlib.bridge.impl.Layout$Builder.findAppCompatActionBar(Layout.java:455)
        at com.android.layoutlib.bridge.impl.Layout$Builder.<init>(Layout.java:422)
        at com.android.layoutlib.bridge.impl.RenderSessionImpl.init(RenderSessionImpl.java:193)
        at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:139)
        ...
```

**Comment by TWiStErRob** [comment]
Same here

**Comment by TWiStErRob** [comment]
Note this also prevents using latest appcompat:
```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.appcompat:appcompat:1.4.0-rc01.
     AAR metadata file: P:\caches\gradle\caches\transforms-3\d97cc1d19fdf1e11426cbbd2bc28f10e\transformed\appcompat-1.4.0-rc01\META-INF\com\android\build\gradle\aar-metadata.properties.
```

**Comment by nicbell** [comment]
I'm experiencing this this too. Can't upgrade most JetPack libraries as they require SDK 31 now.

**Comment by mochadwi** [comment]
same here happened to us! :sob:

**Comment by mochadwi** [comment]
Running via terminal also shows this error:

> command runs: `./gradlew :<our module name>:testDebugUnitTest --tests company.ComponentBannerTest.snapshot`

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by app.cash.paparazzi.Paparazzi (file:~/.gradle/caches/transforms-3/d312ada870b99031bd962c80c3b111f4/transformed/jetified-paparazzi-0.9.3.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of app.cash.paparazzi.Paparazzi
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

company.ComponentBannerTest > snapshot FAILED
    java.lang.ExceptionInInitializerError at AutofillManager.java:252
        Caused by: java.lang.ArrayIndexOutOfBoundsException at Build.java:227
```

Our test files:

```
class ComponentBannerTest {
    @get:Rule
    val paparazzi = Paparazzi()

    @Test
    fun snapshot() {
        val launch = paparazzi.inflate<ConstraintLayout>(R.layout.component_banner)
        paparazzi.snapshot(launch)
    }
}
```

Our XML

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/banner_root"
    android:layout_width="match_parent"
    android:visibility="gone"
    tools:visibility="visible"
    android:layout_height="wrap_content"
    android:paddingLeft="18dp"
    android:paddingStart="18dp"
    android:paddingTop="16dp"
    android:paddingRight="16dp"
    android:paddingEnd="16dp"
    android:paddingBottom="20dp">

    <ImageView
        android:id="@+id/imageview_empty_logo"
        android:layout_width="24dp"
        android:layout_height="24dp"
        android:adjustViewBounds="true"
        android:scaleType="fitCenter"
        android:layout_marginEnd="16dp"
        android:layout_marginRight="16dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintEnd_toStartOf="@id/textview_empty_description"/>

    <TextView
        android:id="@+id/textview_empty_description"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toTopOf="@id/textview_banner_action"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toEndOf="@id/imageview_empty_logo"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_chainStyle="spread"
        tools:text="@tools:sample/lorem"/>

    <TextView
        android:id="@+id/textview_banner_action"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="16dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toBottomOf="@id/textview_empty_description"
        tools:text="@android:string/ok"/>
</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by int02h** [comment]
Any updates here?

**Comment by ncipollo** [comment]
Hmm, I tried updating to the latest studio tag (`studio-2021.1.1`) but am getting a JNI error when I try and load the native library:

```
SEVERE: broken: Native layoutlib failed to load
java.lang.UnsatisfiedLinkError: unsupported JNI version 0xFFFFFFFF required by ~/.gradle/caches/transforms-3/9db22b925de80d2eefb9d7b596fb4f8f/transformed/layoutlib-native-macosx-2021.1.1-573f0704/data/mac/lib64/libandroid_runtime.dylib
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.android.layoutlib.bridge.Bridge.loadNativeLibraries(Bridge.java:720)
	at com.android.layoutlib.bridge.Bridge.loadNativeLibrariesIfNeeded(Bridge.java:695)
	at com.android.layoutlib.bridge.Bridge.init(Bridge.java:178)
	at app.cash.paparazzi.internal.Renderer.prepare(Renderer.kt:84)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:133)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:106)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	...
```

I noticed that the prebuilt libraries now have an additional native artifact in them - `libc++.dylib` (ex - https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/refs/tags/studio-2021.1.1/data/mac/lib64). I tried loading this in prior to loading `libandroid_runtime.dylib` but no dice, it still failed with the same error.

I also tried the latest from google master mirror (`9e08633259`) and it also had the same issue. 

Has anyone experienced this issue before and know how to get around it?

**Comment by jrodbx** [comment]
> Has anyone experienced this issue before and know how to get around it?

This particular issue is related to a filename change of the icu data file: 

https://github.com/cashapp/paparazzi/pull/375/files?file-filters%5B%5D=.kt&show-viewed-files=true#diff-387bfa20d3d3ea21a6701268b5ca1c777f7ef79f849f99277da62fffdc3b0d14
