### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by sdoward** [cashapp/paparazzi#351]
When running `recordPaparazzi` I see the following error.

I can only find a reference to IStart in  `CamColor.java` in androidx.core. 

```
java.lang.NoSuchFieldError: lStar
	at org.sharethemeal.android.view.R$styleable.<clinit>(Unknown Source)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at app.cash.paparazzi.internal.PaparazziCallback.initResources(PaparazziCallback.kt:73)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:128)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:106)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
```

**Comment by sdoward** [comment]
This issue only seems to be present on version 1.7.0 of the androidx lib 1.6.0 works correctly

**Comment by mochadwi** [comment]
> This issue only seems to be present on version 1.7.0 of the androidx lib 1.6.0 works correctly

how to use androidx lib 1.6.0?

**Comment by sdoward** [comment]
@mochadwi I might have been wrong with that. I am currently using with 1.5.0

**Comment by mochadwi** [comment]
well noted, which dependency should we point to 1.5.0? does it only `androidx.core`? 

<img width="370" alt="Screen Shot 2022-01-30 at 5 49 52 PM" src="https://user-images.githubusercontent.com/7057959/151696578-b3a7c91e-1b17-48f5-8562-7766fbb8c013.png">

**Comment by sdoward** [comment]
`androidx.core` is the one that cause the initial problems for me. But be aware you might have transitive dependencies using higher version

**Comment by mochadwi** [comment]
Our current workaround:

1. we are using https://github.com/jmfayard/refreshVersions/, 
2. we use the `androidx.core=1.7.0` in `versions.properties` (used by `refereshVersions`
3. in our ui library, i.e: `:ui-component/build.gradle` we use following:

```
   testImplementation(AndroidX.core) {
        version { strictly("1.5.0") }
        because("Issue with cashapp/paparazzi, see: https://github.com/cashapp/paparazzi/issues/351")
    }
```

works in our ends 🙏

**Comment by jrodbx** [comment]
Duplicate/related to https://github.com/cashapp/paparazzi/issues/264

androidx.core 1.7+ seems to have a dependency on Android S.  Two examples I've seen so far is the one referenced by the OP and the following:
```
java.lang.NullPointerException
    at androidx.core.os.BuildCompat.isAtLeastPreReleaseCodename(BuildCompat.java:57)
    at androidx.core.os.BuildCompat.isAtLeastS(BuildCompat.java:166)
    at androidx.core.widget.EdgeEffectCompat.create(EdgeEffectCompat.java:66)
    at androidx.core.widget.NestedScrollView.<init>(NestedScrollView.java:213)
    at androidx.core.widget.NestedScrollView.<init>(NestedScrollView.java:207)
    at androidx.core.widget.NestedScrollView.<init>(NestedScrollView.java:203)
```

The workaround at the moment is to restrict to androidx.core 1.6, in all direct and indirect dependencies.

I'll try to prioritize bumping to the new layoutlib now that Bumblebee has reached final release.

**Comment by andersu** [comment]
Haven't had this issue for a while, but after updating this dependency  to 1.9.0 today
`implementation androidx.core:core-ktx:1.9.0`
I also got 
```
java.lang.NullPointerException
	at androidx.core.os.BuildCompat.isAtLeastPreReleaseCodename(BuildCompat.java:60)
	...
```
and this fixed it: 
```
    implementation("androidx.core:core") {
        version { strictly("1.8.0") }
        because("Issue with cashapp/paparazzi, see: https://github.com/cashapp/paparazzi/issues/351")
    }
 ```
