### ISSUE TITLE
Bumblebee Layoutlib doesn't stub out InputMethodManager properly

### ISSUE THREAD

**Issue by jrodbx** [cashapp/paparazzi#407]
The Bumblebee version of layoutlib now returns an InputMethodManager via getSystemService when requested.
While layoutlib does attempt to stub it out, it unfortunately doesn't do so correctly:

Example stack trace:
```
INFO: imeTracing [4]: Exception while creating ImeTracing instance
android.os.ServiceManager$ServiceNotFoundException: No service published for: input_method
at android.os.ServiceManager.getServiceOrThrow(ServiceManager.java:37)
at android.util.imetracing.ImeTracing.(ImeTracing.java:61)
at android.util.imetracing.ImeTracingClientImpl.(ImeTracingClientImpl.java:33)
at android.util.imetracing.ImeTracing.getInstance(ImeTracing.java:75)
at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1746)
at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1740)
at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1709)
at com.squareup.util.android.Keyboards.hideKeyboard(Keyboards.kt:23)
at com.squareup.util.android.Keyboards.hideKeyboard(Keyboards.kt:13)
at com.squareup.cash.mooncake.components.AlertDialogView.onAttachedToWindow(AlertDialogView.kt:75)
```

While method interception or an upstream fix is likely the long-term solution, for now, our internal workaround is to avoid it in tests so:

```
open class AlertDialogView @JvmOverloads constructor(
  context: Context,
  attrs: AttributeSet? = null,
  private val hideKeyboard: Boolean = true
) : FrameLayout(context, attrs) {

  ...

  override fun onAttachedToWindow() {
    super.onAttachedToWindow()

    if (hideKeyboard) {
      val inputMethodManager = context.getSystemService(InputMethodManager::class.java)
      inputMethodManager.hideSoftInputFromWindow(this.windowToken, 0)
    }
  }
```

and passing `hideKeyboard = false` in the paparazzi test.

**Comment by jrodbx** [comment]
In layoutlib's bundled `InputMethodManager.java`

```
  static boolean isInEditMode_Original() {
    return false;
  }

  @LayoutlibDelegate
  private static boolean isInEditMode() {
    return InputMethodManager_Delegate.isInEditMode();
  }

  private static InputMethodManager createInstance(int displayId, Looper looper) {
    return isInEditMode() ? createStubInstance(displayId, looper) : createRealInstance(displayId, looper);
  }

  private static InputMethodManager createRealInstance(int displayId, Looper looper) {
    IInputMethodManager service;
```

so paparazzi will use the "stub instance"
