### ISSUE TITLE
NPE on res.getXml()

### ISSUE THREAD

**Issue by hrach** [cashapp/paparazzi#456]
**Description**

I have a composable with 

```kotlin
val animatedImage = AnimatedImageVector.animatedVectorResource(R.drawable.avd_check)
```

A simple testing with

```kotlin
paparazzi.snapshot { MyComposable() }
```

causes a unit test crash:

```
    java.lang.NullPointerException: res.getXml(resId) must not be null
        at androidx.compose.animation.graphics.res.AnimatorResources_androidKt.loadAnimatorResource(AnimatorResources.android.kt:52)
        at androidx.compose.animation.graphics.vector.compat.XmlAnimatedVectorParser_androidKt.parseAnimatedVectorTarget(XmlAnimatedVectorParser.android.kt:44)
        at androidx.compose.animation.graphics.vector.compat.XmlAnimatedVectorParser_androidKt.parseAnimatedImageVector(XmlAnimatedVectorParser.android.kt:70)
        at androidx.compose.animation.graphics.res.AnimatedVectorResources_androidKt.loadAnimatedVectorResource(AnimatedVectorResources.android.kt:61)
        at androidx.compose.animation.graphics.res.AnimatedVectorResources_androidKt.animatedVectorResource(AnimatedVectorResources.android.kt:48)
        at kiwi.orbit.compose.ui.controls.CheckboxKt.Checkbox(Checkbox.kt:109)
```

**Steps to Reproduce**

```kotlin
paparazzi.snapshot { AnimatedImageVector.animatedVectorResource(R.drawable.avd_check) }
```

**Expected behavior**
No crash

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: Windows
- Compile SDK: 32
- Gradle Version: 7.4.1
- Android Gradle Plugin Version: 7.2.0

**Comment by fcduarte** [comment]
I was able to reproduce this issue with the following steps:

1. Created an animated vector drawable using the samples from https://developer.android.com/guide/topics/graphics/drawable-animation
2. Added `implementation 'androidx.compose.animation:animation-graphics:1.1.1'` to `sample/build.gradle`
3. On `sample/src/test/java/app/cash/paparazzi/sample/HelloComposeTest.kt`, created a new test:
````
  @OptIn(ExperimentalAnimationGraphicsApi::class)
  @Test
  fun testAnimatedDrawable() {
    paparazzi.snapshot("resIssue") { AnimatedImageVector.animatedVectorResource(R.drawable.animatorvectordrawable) }
  }
````

**Comment by fcduarte** [comment]
Two interesting notes:

1. Applying the changes from #471 solves the issue.
2. Bumping `androidx.compose.animation:animation-graphics` to `1.2.0` give a whole different error:
````
Receiver class androidx.compose.ui.platform.AndroidUiFrameClock does not define or inherit an implementation of the resolved method 'abstract kotlin.coroutines.CoroutineContext$Key getKey()' of interface kotlin.coroutines.CoroutineContext$Element.
        at kotlin.coroutines.CoroutineContext$plus$1.invoke(CoroutineContext.kt:33)
        at kotlin.coroutines.CoroutineContext$plus$1.invoke(CoroutineContext.kt:32)
        at kotlin.coroutines.CoroutineContext$Element$DefaultImpls.fold(CoroutineContext.kt:70)
        at androidx.compose.runtime.MonotonicFrameClock$DefaultImpls.fold(MonotonicFrameClock.kt:27)
        at androidx.compose.ui.platform.AndroidUiFrameClock.fold(AndroidUiFrameClock.android.kt:24)
        at kotlin.coroutines.CoroutineContext$DefaultImpls.plus(CoroutineContext.kt:32)
        at kotlin.coroutines.CoroutineContext$Element$DefaultImpls.plus(CoroutineContext.kt:59)
        at kotlin.coroutines.AbstractCoroutineContextElement.plus(CoroutineContextImpl.kt:14)
        at androidx.compose.ui.platform.AndroidUiDispatcher$Companion$Main$2.invoke(AndroidUiDispatcher.android.kt:162)
        at androidx.compose.ui.platform.AndroidUiDispatcher$Companion$Main$2.invoke(AndroidUiDispatcher.android.kt:155)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.compose.ui.platform.AndroidUiDispatcher$Companion.getMain(AndroidUiDispatcher.android.kt:155)
        at androidx.compose.ui.platform.AndroidUiDispatcher$Companion.getCurrentThread(AndroidUiDispatcher.android.kt:184)
        at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:333)
        at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:324)
        at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:168)
        at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224)
        at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:299)
        at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:240)
        at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:247)
        at androidx.compose.ui.platform.AbstractComposeView.onAttachedToWindow(ComposeView.android.kt:279)
        at android.view.View.dispatchAttachedToWindow(View.java:20753)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5290)
        at android.view.ViewGroup.addView(ViewGroup.java:5076)
        at android.view.ViewGroup.addView(ViewGroup.java:5016)
        at android.view.ViewGroup.addView(ViewGroup.java:4988)
        at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:290)
        at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:209)
        at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:202)
        at app.cash.paparazzi.sample.HelloComposeTest.compose(HelloComposeTest.kt:28)
````

**Comment by hrach** [comment]
The different error seems to be caused just by upgrading animations only.
