### ISSUE TITLE
IllegalStateException: Failed to init Bridge caused by UnsatisfiedLinkError: Can't load library

### ISSUE THREAD

**Issue by eboudrant** [cashapp/paparazzi#495]
**Description**
On our CI we have "intermittent" failures on Paparazzi, the error is : 
```
java.lang.IllegalStateException: Failed to init Bridge.
	at app.cash.paparazzi.internal.Renderer.prepare(Renderer.kt:83)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:158)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:122)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:420)
	at ...
```
Which is caused by
```
Jul 12, 2022 5:16:01 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: broken: Native layoutlib failed to load
java.lang.UnsatisfiedLinkError: Can't load library: /agent/workspace/Project-ABC/label/awstest_android/my_variants/unitTestDebug/.gradle/caches/transforms-3/57eded7ec1aadfb67857557a846e1fd3/transformed/layoutlib-native-linux-2021.1.1-573f070/data/linux/lib64/libandroid_runtime.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.android.layoutlib.bridge.Bridge.loadNativeLibraries(Bridge.java:720)
	at com.android.layoutlib.bridge.Bridge.loadNativeLibrariesIfNeeded(Bridge.java:695)
	at com.android.layoutlib.bridge.Bridge.init(Bridge.java:178)
	at app.cash.paparazzi.internal.Renderer.prepare(Renderer.kt:84)
```

The `libandroid_runtime.so` is definitely not present in the `/agent/workspace/Project-ABC/.../lib64/` folder. 

What's also interesting, the `/agent/workspace/Project-ABC/` folder is not where the build is supposed, this is another build project (running on another CI agent). That's probably why the `.so` file does not exists.

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: Linux 5.4.0-1080-aws
- Compile SDK: 31
- Gradle Version: 7.4.2
- Android Gradle Plugin Version: 7.2.1

**Comment by eboudrant** [comment]
The problem is line 6 of `resources.txt`, value of `configurations.unzip.singleFile.path`. 

On a local machine the file exists (ex : `/Users/eboudrant/.gradle/caches/transforms-3/f1536f6c97f772845ea671ab61867793/transformed/layoutlib-native-macarm-2021.1.1-573f070`).

On CI the file does not exists (ex: `/mnt/data/agent/workspace/Project-ABC/label/awstest_android/my_variants/unitTestDebug/.gradle/caches/transforms-3/57eded7ec1aadfb67857557a846e1fd3/transformed/layoutlib-native-linux-2021.1.1-573f070/data/linux/lib64/libandroid_runtime.so`

I'm not super familiar where `configurations.unzip.singleFile.path` get its value from, I need to investigate that...

**Comment by eboudrant** [comment]
After investigation I suspect a build cache issue, I tried by removing `@CacheableTask` from `PrepareResourcesTask` and the build passes. Looks like the value of `platformDataRoot` is not invalidating the cache when changed, that's a bit odd considering it's annotated as `@InputDirectory`.

**Comment by eboudrant** [comment]
Steps to reproduce with the sample app:
- First run `./gradlew clean :sample:recordPaparazzi` so we can run verify task later
- make sure build cache is enabled (local or remote)
- set a new gradle home, ex `/Users/eboudrant/gh_1`
- run `./gradlew clean :sample:verifyPaparazzi` -> `SUCCESS`
- set a new gradle home, ex `/Users/eboudrant/gh_2`
- delete the old gradle home (`/Users/eboudrant/gh_1`)
- run `./gradlew clean :sample:verifyPaparazzi` -> `FAILED`

Failure root cause is:
```
java.lang.UnsatisfiedLinkError: Can't load library: /Users/eboudrant/gh_1/caches/transforms-3/f1536f6c97f772845ea671ab61867793/transformed/layoutlib-native-macarm-2021.1.1-573f070/data/mac-arm/lib64/libandroid_runtime.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
```

After investigation, here the value added in build cache for the `paparazziResources` task:
```
L1 app.cash.paparazzi.sample
L2 build/intermediates/merged_res/debug
L3 31
L4 platforms/android-31/
L5 build/intermediates/assets/debug/mergeDebugAssets
L6 /Users/eboudrant/gh_1/caches/transforms-3/f1536f6c97f772845ea671ab61867793/transformed/layoutlib-native-macarm-2021.1.1-573f070
L7 app.cash.paparazzi.sample
```
The problem is on line 6, it contains an absolute path to the gradle home used during the test. 
If the machine you run the test have a different gradle home that the one that stored the result in cache it will fail.
