### ISSUE TITLE
Advice on a Compose Accessibility Extension

### ISSUE THREAD

**Issue by yschimke** [cashapp/paparazzi#551]
**Description**

I wanted to use the AccessibilityRenderExtension with Compose.  But it doesn't seem to find anything.

So I tried writing a new one using the same mechanics as the ComposeTestRule. But I got a bit stuck, looking for some advice.

https://gist.github.com/yschimke/b848e35c05f371680d38b7c1949257d6

**Steps to Reproduce**

https://gist.github.com/yschimke/b848e35c05f371680d38b7c1949257d6

```
java.lang.Exception: renderView
	at com.google.android.horologist.audio.ui.ComposeA11yExtension.renderView(ComposeA11yExtension.kt:86)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:283)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:211)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:204)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:195)
	at com.google.android.horologist.audio.ui.VolumeScreenA11yTest.volumeScreenAtMinimums(VolumeScreenA11yTest.kt:47)
...
Aug 24, 2022 5:50:43 PM app.cash.paparazzi.internal.PaparazziLogger warning
WARNING: resources.format: You must supply a layout_width attribute.
Aug 24, 2022 5:50:43 PM app.cash.paparazzi.internal.PaparazziLogger warning
WARNING: resources.format: You must supply a layout_height attribute.
Aug 24, 2022 5:50:43 PM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
INFO: Settings [3]: Can't get key animator_duration_scale from content://settings/global
Aug 24, 2022 5:50:43 PM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
INFO: Settings [3]: Can't get key user_rotation from content://settings/system
java.lang.Exception: Attach
	at com.google.android.horologist.audio.ui.ComposeA11yExtension$1$1.onViewAttachedToWindow(ComposeA11yExtension.kt:38)
	at android.view.View.dispatchAttachedToWindow(View.java:20764)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5290)
	at android.view.ViewGroup.addView(ViewGroup.java:5076)
	at android.view.ViewGroup.addView(ViewGroup.java:5016)
	at android.view.ViewGroup.addView(ViewGroup.java:4988)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:292)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:211)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:204)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:195)
	at com.google.android.horologist.audio.ui.VolumeScreenA11yTest.volumeScreenAtMinimums(VolumeScreenA11yTest.kt:47)
...
Position: Offset(0.0, 44.0) 52 x 0
Content Description [Increase Volume]
Position: Offset(64.0, 28.0) 152 x 0
Content Description [Pixelbuds]
State Description Connected, Volume 0
On Click Change Audio Output
Position: Offset(0.0, 32.0) 52 x 0
Content Description [Decrease Volume]
```

**Expected behavior**

The onViewAttachedToWindow methods are called before renderView, so I can build the view in response.

As you can see I get the data I need, the "Position", "Content Description", "State Descriptions" and "On Click".  But don't now how to structure it.

**Comment by yschimke** [comment]
I think I've got the ordering working, by creating the empty accessibility view.  

I think I'm stuck on attaching the input contentView into the returned LinearLayout, for some reasons it's not displaying.

I'll keep testing.

**Comment by yschimke** [comment]
Seems to not be displayed as the contentView doesn't have a size at the point of renderView.  But if I hardcode it for testing, I can get it laying out.

Next up, add a relative layout and render the colour boxes on top the contentView.

**Comment by yschimke** [comment]
@jrodbx A question on any of these feature that stitch together images, with labels etc.  Should I use skia java bindings, will that give me better results across OSX/linux.

**Comment by geoff-powell** [comment]
Closing as this was fixed with https://github.com/cashapp/paparazzi/pull/702
