### ISSUE TITLE
Issue with API 32 or 33 with Coil

### ISSUE THREAD

**Issue by yschimke** [cashapp/paparazzi#593]
**Description**

```
java.lang.NullPointerException
	at androidx.core.os.BuildCompat.isAtLeastPreReleaseCodename(BuildCompat.java:60)
	at androidx.core.os.BuildCompat.isAtLeastT(BuildCompat.java:211)
	at androidx.core.content.ContextCompat.checkSelfPermission(ContextCompat.java:595)
	at coil.util.-Contexts.isPermissionGranted(Contexts.kt:81)
	at coil.network.NetworkObserverKt.NetworkObserver(NetworkObserver.kt:27)
	at coil.util.SystemCallbacks.<init>(SystemCallbacks.kt:31)
	at coil.RealImageLoader.<init>(RealImageLoader.kt:79)
	at coil.ImageLoader$Builder.build(ImageLoader.kt:529)
	at coil.ImageLoaders.create(ImageLoaders.kt:16)
	at coil.Coil.newImageLoader(Coil.kt:64)
	at coil.Coil.imageLoader(Coil.kt:29)
	at coil.compose.ImageLoaderProvidableCompositionLocal.getCurrent(LocalImageLoader.kt:57)
	at coil.compose.SingletonAsyncImagePainterKt.rememberAsyncImagePainter-MqR-F_0(SingletonAsyncImagePainter.kt:57)
	at com.google.android.horologist.media.ui.components.MediaArtworkKt.MediaArtwork(MediaArtwork.kt:53)
	at com.google.android.horologist.media.ui.components.MediaChipKt$MediaChip$appIcon$1$1.invoke(MediaChip.kt:80)
	at com.google.android.horologist.media.ui.components.MediaChipKt$MediaChip$appIcon$1$1.invoke(MediaChip.kt:79)
```

Method is

```
    protected static boolean isAtLeastPreReleaseCodename(@NonNull String codename,
            @NonNull String buildCodename) {

        // Special case "REL", which means the build is not a pre-release build.
        if ("REL".equals(buildCodename)) {
            return false;
        }

        // Otherwise lexically compare them.  Return true if the build codename is equal to or
        // greater than the requested codename.
        final String buildCodenameUpper = buildCodename.toUpperCase(Locale.ROOT);
        final String codenameUpper = codename.toUpperCase(Locale.ROOT);
        return buildCodenameUpper.compareTo(codenameUpper) >= 0;
    }
```

**Steps to Reproduce**

Bump project compileSdk to 33 and configure SDK 32 in Paparazzi.

**Expected behavior**

Image loaders work, or at least don't fail.

**Workaround**

I created a FakeImageLoader for tests.  Coil also allows you to disable the network observer.

**Additional information:**
- Paparazzi Version: 1.0
- OS: github linux
- Compile SDK: 33
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.3.0

**Comment by yschimke** [comment]
Another issue which I suspect is related.  Resources not loading, probably because of this version specific code in Coil.

https://github.com/coil-kt/coil/blob/f35ef73fc76a166697431e6dd3c20d2d853bc353/coil-base/src/main/java/coil/util/Contexts.kt

**Comment by yschimke** [comment]
Looks like I can override Coil Fetchers to use a simpler codepath.  https://coil-kt.github.io/coil/image_pipeline/

And I can either replace the RealImageLoader or disable isNetworkObserverEnabled.

So I shouldn't be blocked here.

Leaving open since Coil is executing valid code.

**Comment by colinrtwhite** [comment]
Does this fail with any usage of `ContextCompat.checkSelfPermission`? Also does it work with Coil `2.2.0`? Coil bumped compile SDK to 33 in `2.2.1`.

**Comment by yschimke** [comment]
Yep, Any call to ContextCompat.checkSelfPermission will fail.  Coil is just the first thing calling it, and I guess most other things are not done in the Composable.

I'm not sure if it's Coil's compile SDK that the problem.  Here I'm using compileSdk because compose 1.3-alpha requires it.

There is a rich seam of related errors, so not Coil specific, but Coil triggers it sooner.  Luckily the test ImageLoader approach works well.

**Comment by TWiStErRob** [comment]
Looks like this is also one for #604, @jrodbx.
