### ISSUE TITLE
ConcurrentModificationException when running a lot of tests at once

### ISSUE THREAD

**Issue by agrosner** [cashapp/paparazzi#610]
**Description**
We have a lot of modules, so we run our tests in parallel all at once. We have about 10 modules using paparazzi. Occasionally, the tests for Paparazzi will fail with:

```
java.util.ConcurrentModificationException
	at java.base/java.util.WeakHashMap.forEach(WeakHashMap.java:1031)
	at com.android.layoutlib.bridge.util.HandlerMessageQueue.extractFirst(HandlerMessageQueue.java:73)
	at android.os.Handler_Delegate.executeCallbacks(Handler_Delegate.java:95)
	at app.cash.paparazzi.Paparazzi.withTime(Paparazzi.kt:330)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:295)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:211)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:204)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:195)
```

Seems as though this line:
```kotlin
Handler_Delegate.executeCallbacks()
```
Cannot handle multiple calls at once. My best suggestion is to synchronize this block so that it allows the concurrency to succeed.

**Steps to Reproduce**
Can't share my work repo. I imagine a project with a few modules, and running `testDebugUnitTest` on the top level project.

**Expected behavior**
Should successfully run.

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: macOS Monterey 12.6
- Compile SDK: 32
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.2.1

JDK:
```
openjdk 11.0.16.1 2022-08-12 LTS
OpenJDK Runtime Environment Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS, mixed mode)
```

**Comment by jrodbx** [comment]
> Can't share my work repo. I imagine a project with a few modules, and running testDebugUnitTest on the top level project.

Understandable that you can't share your work repo, but could you please make a sample?  Bug issues with samples get love faster.

**Comment by elihart** [comment]
We have also encountered this

**Comment by jrodbx** [comment]
Closed by https://github.com/cashapp/paparazzi/pull/645
