### ISSUE TITLE
applying paparazzi to module breaks robolectric tests

### ISSUE THREAD

**Issue by tordjon** [cashapp/paparazzi#622]
**Description**
When I apply the paparazzi plugin to a module containing robolectric tests, the robolectric tests fail with the following error:

```'org.hamcrest.Matcher org.hamcrest.core.AllOf.allOf(org.hamcrest.Matcher, org.hamcrest.Matcher)'
java.lang.NoSuchMethodError: 'org.hamcrest.Matcher org.hamcrest.core.AllOf.allOf(org.hamcrest.Matcher, org.hamcrest.Matcher)'
	at org.hamcrest.Matchers.allOf(Matchers.java:33)
	at androidx.test.espresso.Espresso.<clinit>(Espresso.java:4)
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
```

**Steps to Reproduce**
I have made a repro project: https://github.com/tordjon/PaparazziRobolectricRepro
Run `RobolectricComposeUiTest`, and it should pass. Uncomment :paparazziuser build.gradle line 47, rerun the test and it now fails.

**Expected behavior**
While paparazzi is great, and reduces the need for testing with robolectric, I still want to have both. I expect being able to apply paparazzi to a module containing robolectric tests.

**Additional information:**
- Paparazzi Version: 1.1.0
- OS: macOS monterey 12.6 (21G115)
- Compile SDK: 31-33
- Gradle Version: see repro
- Android Gradle Plugin Version: see repro

**Comment by anidhamal** [comment]
Seeing similar issue with Roboelectric tests

```
java.lang.NoClassDefFoundError: Could not initialize class androidx.test.espresso.Espresso
	at androidx.compose.ui.test.junit4.android.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:91)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:69)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:51)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:51)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule.waitForIdle(AndroidComposeTestRule.android.kt:289)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule.waitForIdle(AndroidComposeTestRule.android.kt:282)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule.setContent(AndroidComposeTestRule.android.kt:277)```

**Comment by alashow** [comment]
Is this expected to be fixed in 1.2.0? Have to create a separate module for paparazzi otherwise because our testing modules use Roboelectric. /cc @jrodbx

**Comment by gamepro65** [comment]
Looks like the Layoutlib prebuilt is [packaging](https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/5128371/layoutlib.jar.manifest#23391) an older version of hamcrest along with itself which is whats causing the runtime crash. Adding an explicit dependency on `testImplementation 'org.hamcrest:hamcrest-core:1.3'` works around the issue in the repro project.

**Comment by jrodbx** [comment]
Closing as this solve @tordjon's original issue.  @anidhamal if the issue still exists for you, could you please refile with a repro?  The stack trace you provided is not the same as the OP, so this should be considered a separate issue.

**Comment by TWiStErRob** [comment]
@jrodbx @gamepro65 Rather than users of Paparazzi having to discover this issue and find a workaround, would it make sense to adjust the pom of layoutlib to do this automatically? or even just exclude those classes from layoutlib jar before publishing?

**Comment by jrodbx** [comment]
Filed https://issuetracker.google.com/issues/318982330 on Google's tracker.  I'd accept a PR to exclude the classes from layoutlib jar before publishing, if tests pass.

**Comment by jrodbx** [comment]
Looks like this is now fixed in Layoutlib per: https://issuetracker.google.com/issues/318982330#comment2

This issue is therefore linked to https://github.com/cashapp/paparazzi/issues/1221
