### ISSUE TITLE
Test failing due to attributes not found in the theme

### ISSUE THREAD

**Issue by anidhamal** [cashapp/paparazzi#626]
**Description**
Unable to get attributes from the theme. Getting following error while running test.
```
java.lang.AssertionError
	at com.android.ide.common.rendering.api.StyleResourceValueImpl.getItem(StyleResourceValueImpl.java:104)
	at com.android.ide.common.resources.ResourceResolver.findItemInStyle(ResourceResolver.java:356)
	at com.android.ide.common.resources.ResourceResolver.findItemInStyle(ResourceResolver.java:60)
	at com.android.ide.common.rendering.api.RenderResources.findItemInTheme(RenderResources.java:83)
	at com.android.layoutlib.bridge.android.BridgeContext.internalObtainStyledAttributes(BridgeContext.java:835)
	at android.content.res.Resources_Theme_Delegate.obtainStyledAttributes(Resources_Theme_Delegate.java:84)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java:1668)
	at android.content.Context.obtainStyledAttributes(Context.java:844)
	at app.cash.paparazzi.sample.CustomButton.setStyle(CustomButton.java:38)
	at app.cash.paparazzi.sample.CustomButton.<init>(CustomButton.java:24)
	at app.cash.paparazzi.sample.HelloComposeTestKt$HelloPaparazzi$1.invoke(HelloComposeTest.kt:25)
	at app.cash.paparazzi.sample.HelloComposeTestKt$HelloPaparazzi$1.invoke(HelloComposeTest.kt:23)
	at androidx.compose.ui.viewinterop.ViewFactoryHolder.setFactory(AndroidView.android.kt:174)
	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$1.invoke(AndroidView.android.kt:116)
	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$1.invoke(AndroidView.android.kt:113)
	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$$inlined$ComposeNode$1.invoke(Composables.kt:254)
	at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(Composer.kt:1537)
	at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(Composer.kt:1535)
	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3395)
	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3392)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:782)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:813)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:827)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1015)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1102)
	at android.view.View.dispatchAttachedToWindow(View.java:20753)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5290)
	at android.view.ViewGroup.addView(ViewGroup.java:5076)
	at android.view.ViewGroup.addView(ViewGroup.java:5016)
	at android.view.ViewGroup.addView(ViewGroup.java:4988)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:291)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:210)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:202)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:191)
	at app.cash.paparazzi.sample.HelloComposeTest.compose(HelloComposeTest.kt:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:120)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Steps to Reproduce**
Sample Project ::
https://github.com/anidhamal/paparazzi/tree/customComponentStyleIssue/sample

- Run `HelloComposeTest` from `Sample` module. It uses custom view inside Compose 
(AndroidView) and passes style to custom view through ContextThemeWrapper.
- Test fails

**Expected behavior**
Test should run and pass as Sample app runs fine with this customview.
- Update build.gradle to use `sample` as `app` (Uncomment lines)  https://github.com/anidhamal/paparazzi/blob/customComponentStyleIssue/sample/build.gradle
- Run the Sample project
- Activity is launched which uses Custom View (**CustomButton**) 

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: Mac OS (12.6.1)
- Compile SDK: 32
- Gradle Version: 7.5.1
- Android Gradle Plugin Version: 7.1.2

**Comment by geoff-powell** [comment]
Just pulled your repo and created a branch that mimics your changes. 
https://github.com/cashapp/paparazzi/tree/gpowell/repro-custom

Looks like the resource rewrite done in the last few versions seem to have fixed this issue (since it was reported on version 1.0.0)
