### ISSUE TITLE
Compose 1.3.0 & Row loop cause OutOfMemoryError

### ISSUE THREAD

**Issue by Masaki-U** [cashapp/paparazzi#675]
**Description**
Failed recordPaparazzi command include specified layout.

**Steps to Reproduce**

1. Add 'Bug Sample Specified Layout'
2. Run recordPaparazziHoge
3. Failed OutOfMemoryError

**Expected behavior**
Success take a Screen Shot.

**Additional information:**
- Paparazzi Version: 1.1.0
- OS: Mac OSX
- Compile SDK: 33
- Gradle Version: 7.6
- Android Gradle Plugin Version: 7.4.0-rc01

Bug Sample Specified Layout

```
@Preview
@Composable
fun Preview() {
    Column {
        listOf(
            "test1",
            "test2",
        ).forEach {
            Row {
                Text(it)
            }
        }
    }
}
```

ErrorLog

```
      java.lang.OutOfMemoryError: Java heap space
        at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
        at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
        at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
        at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
        at app.cash.paparazzi.internal.ImageUtils.scale(ImageUtils.kt:300)
        at app.cash.paparazzi.Paparazzi.scaleImage(Paparazzi.kt:397)
        at app.cash.paparazzi.Paparazzi.access$scaleImage(Paparazzi.kt:83)
        at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:313)
        at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:306)
        at app.cash.paparazzi.Paparazzi.withTime(Paparazzi.kt:347)
        at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:306)
        at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:222)
        at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:221)
        at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:214)
        at jp.*.debugtool.screenShot.ComponentPreviewCapture$defaultComponentPreviewCapture$1.snapshot(ComposePreviewCapture.kt:36)
        at jp.co.*.extensions.compose.preview.DefaultComponentPreviewCapture.preview_tests(DefaultComponentPreviewCapture.kt:41)
        at jp.*.debugtool.screenShot.ComponentPreviewCapture.preview_tests(ComposePreviewCapture.kt:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:123)
        at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
        at com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:420)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at app//app.cash.paparazzi.internal.PaparazziLogger.assertNoErrors(PaparazziLogger.kt:115)
        at app//app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:126)
        at app//app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
        at app//com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:420)
        at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
        at java.base@12.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@12.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base@12.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@12.0.1/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

```

**Comment by TWiStErRob** [comment]
Can you please show how you're using Paparazzi in the test class, AND what is your Gradle setup for `Test` tasks? I have a few suspicions off-hand:
 1. your project's Gradle setup is limiting test tasks' `Xmx`.
    We can rule this out, by checking your Gradle config (only you have access).
 2. There's a memory leak in the other tests which happens to manifest in Paparazzi, because it's moving large amounts of memory.
    We can rule this out, by changing the `@Composable` method in some way (e.g. unrolling the for loop)
    ```kotlin
    Column {
        Row { Text("test1") }
        Row { Text("test1") }
    }
    ```
    This will have the same complexity wrt to rendering, so it should fail the same way.
    Then simplifying it to see if it still fails (getting down to "nothing" and still failing would mean other tests are the culprit):
    ```kotlin
    Text("test1")
    ```
 3. There's a leak/problem in Paparazzi.
    Investigating the previous one might lead to a discovery here too.

**Comment by Masaki-U** [comment]
@TWiStErRob 

Thanks reply!

Your suggestion Layout isn't failed.

Gradle Setting
```
android.useAndroidX=true
android.dataBinding.addKtx=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.configureondemand=false
org.gradle.daemon=true
org.gradle.caching=true
```

Test Code

```
package jp.*.debugtool.screenShot

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.platform.LocalInspectionMode
import androidx.compose.ui.unit.Density
import app.cash.paparazzi.DeviceConfig.Companion.PIXEL_5
import app.cash.paparazzi.Paparazzi
import com.airbnb.android.showkase.models.Showkase
import com.airbnb.android.showkase.models.ShowkaseBrowserComponent
import com.google.testing.junit.testparameterinjector.TestParameterInjector
import jp.*.debugtool.getMetadata
import jp.*.presentation.layout.core.theme.AppTheme
import jp.co.*.extensions.compose.preview.MockData
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

class ComponentPreview(
    private val showkaseBrowserComponent: ShowkaseBrowserComponent,
) {
    val content: @Composable () -> Unit = showkaseBrowserComponent.component
    override fun toString(): String =
        showkaseBrowserComponent.group + ":" + showkaseBrowserComponent.componentKey
}

@RunWith(TestParameterInjector::class)
class ComponentPreviewCapture {

    object PreviewProvider {
        fun provideValues(): List<ComponentPreview> =
            Showkase.getMetadata().componentList
                .sortedBy { it.componentKey }
                .map(::ComponentPreview)
    }

    @get:Rule
    val paparazzi = Paparazzi(
        maxPercentDifference = 0.0,
        deviceConfig = PIXEL_5.copy(softButtons = false),
    )

    @Test
    fun preview_tests() {
        val r = Runtime.getRuntime()
        println("maxMemory  : " + r.maxMemory())
        println("totalMemory: " + r.totalMemory())
        PreviewProvider.provideValues().forEach { componentPreview ->
            parameterList.forEachIndexed { index, parameter ->
                paparazzi.snapshot(componentPreview.toString().plus("_").plus(index)) {
                    CompositionLocalProvider(
                        LocalInspectionMode provides true,
                        LocalDensity provides Density(
                            density = LocalDensity.current.density,
                            fontScale = parameter.fontScale
                        )
                    ) {
                        AppTheme(parameter.isDarkTheme) {
                            componentPreview.content()
                        }
                    }
                }
            }
        }
    }

    private val parameterList = listOf(1.0F, 1.5F).flatMap { fontScale ->
        MockData.Boolean.map { isDarkTheme ->
            Parameter(
                fontScale = fontScale,
                isDarkTheme = isDarkTheme,
            )
        }
    }

    data class Parameter(
        val fontScale: Float,
        val isDarkTheme: Boolean,
    )
}
```

**Comment by nuhkoca** [comment]
We recently faced the same problem and  allocating more memory for the test task solved it


```kotlin
testOptions { 
     unitTests { 
         all { 
             it.maxHeapSize = "1G" 
         } 
     } 
 }
```

**Comment by TWiStErRob** [comment]
Because of the loop **inside** the test, it is actually possible there's a leak in Paparazzi somewhere. Looks like John is looking. 🙇‍♂️

In the meantime, I would recommend trying a [test parameterization method](https://github.com/junit-team/junit4/wiki/parameterized-tests) and run each preview as a separate test, so Paparazzi can be set up and torn down between each shot. This has the added benefit of better failure handling. There would be a clear indication of which preview(s) failed and all the others would be still generated.

**Comment by sorinirimies** [comment]
> We recently faced the same problem and allocating more memory for the test task solved it
> 
> ```kotlin
> testOptions { 
>      unitTests { 
>          all { 
>              it.maxHeapSize = "1G" 
>          } 
>      } 
>  }
> ```

This just hides the memory leak issue.

**Comment by Masaki-U** [comment]
@jrodbx cc: @sorinirimies 
Hi, Fixed my project.

First, Change to parameterized Test is not resolved.
Important modify is stop shared Paparazzi instance.
 
Each screen shots need individual Paparazzi instances.

Base Class
https://github.com/arsaga-partners/AndroidComposeExtension/blob/master/src/main/java/jp/co/arsaga/extensions/compose/preview/DefaultComponentPreviewCapture.kt

```
package jp.arsaga.debugtool.screenShot

import androidx.compose.runtime.Composable
import app.cash.paparazzi.DeviceConfig.Companion.PIXEL_5
import app.cash.paparazzi.Paparazzi
import com.airbnb.android.showkase.models.Showkase
import com.airbnb.android.showkase.models.ShowkaseElementsMetadata
import com.google.testing.junit.testparameterinjector.TestParameter
import com.google.testing.junit.testparameterinjector.TestParameterInjector
import jp.arsaga.debugtool.getMetadata
import jp.arsaga.presentation.layout.core.theme.AppTheme
import jp.co.arsaga.extensions.compose.preview.AbstractPreviewProvider
import jp.co.arsaga.extensions.compose.preview.ComponentPreview
import jp.co.arsaga.extensions.compose.preview.DefaultComponentPreviewCapture
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith


@RunWith(TestParameterInjector::class)
class ComponentPreviewCapture {


    class PreviewProvider : AbstractPreviewProvider() {

        override fun metaData(): ShowkaseElementsMetadata = Showkase.getMetadata()

    }


    @Test
    fun preview_tests(
        @TestParameter(valuesProvider = PreviewProvider::class) componentPreview: ComponentPreview,
        @TestParameter(value = ["1.0", "1.5"]) fontScale: Float,
        @TestParameter(value = ["false", "true"]) theme: Boolean,
    ) {

        val paparazzi = Paparazzi(
            maxPercentDifference = 0.0,
            deviceConfig = PIXEL_5.copy(softButtons = false),
        )
        val previewCapture = object : DefaultComponentPreviewCapture() {
            override fun snapshot(fileName: String, content: @Composable () -> Unit) {
                paparazzi.snapshot(fileName, content)
            }

            @Composable
            override fun Theme(isDarkTheme: Boolean, content: @Composable () -> Unit) {
                AppTheme(isDarkTheme, content)
            }
        }
        previewCapture.previewTests(
            componentPreview, fontScale, theme
        )
    }
}
```
