### ISSUE TITLE
java.lang.NoClassDefFoundError while using DataBinding with Paparazzi

### ISSUE THREAD

**Issue by VarunSharma87** [cashapp/paparazzi#700]
While trying to do screenshot testing for a view/xml using DataBiding, I am getting  java.lang.NoClassDefFoundError as in the stacktrace below.
Attaching sample project for reference

java.lang.NoClassDefFoundError: androidx/databinding/DataBinderMapperImpl
	at com.example.mylibrary.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:48)
	at com.example.mylibrary.ExampleUnitTest.validate_main_activity(ExampleUnitTest.kt:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:118)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.ClassNotFoundException: androidx.databinding.DataBinderMapperImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 47 more

[DataBindingWithPaparazzi.zip](https://github.com/cashapp/paparazzi/files/10491007/DataBindingWithPaparazzi.zip)

**Comment by TWiStErRob** [comment]
Confirmed repro on attached project with `gradlew :mylibrary:recordPaparazziDebug`.
I validated that `+--- androidx.databinding:databinding-runtime:7.3.1` is part of `debugUnitTestRuntimeClasspath`.
I realized that `DataBinderMapperImpl` is generated code.

Removed Paparazzi plugin and all related code, and the same exception occurs with this:
```kotlin
val binding = Class.forName("com.example.mylibrary.databinding.ActivityMainBinding")
    .getDeclaredMethod("inflate", LayoutInflater::class.java)
    .invoke(null, null) as ActivityMainBinding
```
```
Caused by: java.lang.NoClassDefFoundError: androidx/databinding/DataBinderMapperImpl
	at com.example.mylibrary.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:48)
	... 48 more
```

Bumped AGP to 7.4.0 and Kotlin to 1.8.0, still repros.
Added `id 'org.jetbrains.kotlin.kapt'`, but still repros.
Noticed that `DataBinderMapperImpl` is in `mylibrary\build\generated\source\kapt\debug\com\example\mylibrary\DataBinderMapperImpl.java`, so it's a different package than what runtime is looking for.

It looks like `androidx.databinding.DataBinderMapperImpl` is only generated for application modules, but we're in a library module here.

**Comment by TWiStErRob** [comment]
Workaround: create `mylibrary/src/main/test/java/androidx/databinding/DataBinderMapperImpl.kt` ourselves.
Note: it must be in the `test` sources otherwise it messes things up.

```kotlin
package androidx.databinding
class DataBinderMapperImpl : MergedDataBinderMapper() {
	init {
		addMapper(androidx.databinding.library.baseAdapters.DataBinderMapperImpl())
	}
}
```
results in
```
java.lang.NullPointerException: inflate(paparazzi.layoutInflater) must not be null
	at com.example.mylibrary.ExampleUnitTest.validate_main_activity(ExampleUnitTest.kt:21)
```
which is really strange, but
```kotlin
package androidx.databinding

class DataBinderMapperImpl : com.example.mylibrary.DataBinderMapperImpl()
```
<details><summary>works. (expand for screenshot)</summary>

![image](https://user-images.githubusercontent.com/2906988/214348357-b77d7323-5f8b-4020-8db8-0a3c3bbda836.png)

</details>

**Comment by VarunSharma87** [comment]
Thanks, @TWiStErRob !
This helps. 
Although later I did see that there is an open issue with jetbrains for the same.
https://youtrack.jetbrains.com/issue/KT-27404

**Comment by TWiStErRob** [comment]
@VarunSharma87 having a workaround does not mean that this is normal and expected.
The issue you linked looks related, but I don't think it is. Here kapt runs, but does not generate the sources because it's a library, not because of source sets.

@jrodbx / @JakeWharton do you think this is fixable in some way inside `PaparazziPlugin`? Because Paparazzi makes a JVM library (test sources) an end-consumer of the main AAR, it might need to set up more of the "app" than AGP does.

**Comment by VarunSharma87** [comment]
@TWiStErRob I closed it due to the reason that it is happening for non-paparazzi unit tests also. Please let me know if you would want me to reopen it.

**Comment by TWiStErRob** [comment]
Let's see what the maintainers say.

**Comment by JakeWharton** [comment]
Yes, this is not our problem. You can appeal to AGP to generate this type automatically in Android source sets of library modules for testing (since they don't propagate downstream).

**Comment by JakeWharton** [comment]
Or write a separate Gradle plugin which does that if AGP won't.
