### ISSUE TITLE
Plugin throws NPE if unit tests were disabled for a variant

### ISSUE THREAD

**Issue by dniHze** [cashapp/paparazzi#711]
**Description**
If the Gradle config of a library module disables unit tests for certain variants, Paparazzi will crash with NullPointerException when searching for the test variant name.

```java
FAILURE: Build failed with an exception.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':some-module.

***

Caused by: java.lang.NullPointerException
	at app.cash.paparazzi.gradle.PaparazziPlugin$setupPaparazzi$1.invoke(PaparazziPlugin.kt:111)
	at app.cash.paparazzi.gradle.PaparazziPlugin$setupPaparazzi$1.invoke(PaparazziPlugin.kt:75)
	at app.cash.paparazzi.gradle.PaparazziPlugin.setupPaparazzi$lambda$2(PaparazziPlugin.kt:75)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
	at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:262)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:251)
	at com.android.build.gradle.LibraryExtension.addVariant(LibraryExtension.kt:102)
	at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:119)
	... 183 **more
```

**Steps to Reproduce**
Disable Unit tests for variants with certain build type:

```kotlin
android {
    androidComponents {
        val release = selector().withBuildType(BuildType.RELEASE.name)
        beforeVariants(release) { variant ->  variant.enableUnitTest = false }
    }
}
```

**Expected behavior**
Plugin applies to variants with enabled tests.

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: MacOS Mojave
- Compile SDK: 33
- Gradle Version: 7.6.0
- Android Gradle Plugin Version: 7.4.0

**Comment by jrodbx** [comment]
Closed by #710
