### ISSUE TITLE
Cannot screenshot material Scaffold

### ISSUE THREAD

**Issue by mattinger** [cashapp/paparazzi#714]
**Description**
Taking a snapshot of a composable with a scaffold will fail the first invocation with the following exception:

```
java.lang.IllegalArgumentException: Can't represent a size of 2147483479 in Constraints
	at androidx.compose.ui.unit.Constraints$Companion.bitsNeedForSize(Constraints.kt:403)
	at androidx.compose.ui.unit.Constraints$Companion.createConstraints-Zbe2FdA$ui_unit_release(Constraints.kt:363)
	at androidx.compose.ui.unit.Constraints.copy-Zbe2FdA(Constraints.kt:173)
	at androidx.compose.ui.unit.Constraints.copy-Zbe2FdA$default(Constraints.kt:158)
	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:319)
	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:243)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:602)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:968)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:953)
```

After that first test fails, any subsequent snapshots taken with a Scaffold will succeed

**Steps to Reproduce**
A simple test case shows this behavior:

```
class ScaffoldsScreenshotTest {
    @get:Rule
    val paparazzi: Paparazzi = Paparazzi(
        theme = "android:Theme.MaterialComponents.Light.NoActionBar",
        deviceConfig = DeviceConfig.NEXUS_5.copy(softButtons = false, screenHeight = 3000),
        renderingMode = SessionParams.RenderingMode.V_SCROLL
    )

    @Test
    fun capture1() {
        paparazzi.snapshot {
            Scaffold(
                modifier = Modifier.fillMaxSize(),
                topBar = {
                    TopAppBar {
                        Text("Title")
                    }
                }
            ) {
                Box(modifier = Modifier.padding(it)) {
                    Text("Body")
                }
            }
        }
    }

    @Test
    fun capture2() {
        paparazzi.snapshot {
            Scaffold(
                modifier = Modifier.fillMaxSize(),
                topBar = {
                    TopAppBar {
                        Text("Title")
                    }
                }
            ) {
                Box(modifier = Modifier.padding(it)) {
                    Text("Body")
                }
            }
        }
    }
}
```

**Expected behavior**
Both test functions execute and succeed.

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: MacOS 12.5
- Compile SDK: 32
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.4
- Compose Compiler: 1.3.2
- Compose: 1.2.1
- Compose Material: 1.2.1
- Material: 1.5.0

**Comment by mattinger** [comment]
UPDATE:  Explicitly giving the scaffold a height measurement seems to let it run.  But i do see the same behavior, where after the first snapshot, everything works fine, even if subsequent snapshots have a fillMaxSize() on the scaffold.

So it seems the first measurement process, whether it succeeds or fails, kicks something into gear that allows it to properly measure on the second go round.

This is also contained per instance of the test rule.  So if you have two different test classes, they have two different rule instances, and both have the same behavior.  So without some explicit sizing both test classes would fail the first measurement

**Comment by mattinger** [comment]
I've also had success surrounding the scaffold with an explicitly sized box instead, so that it's parent has a pre-determined measure size to pass along to the children who want to use fillMaxSize()

**Comment by jrodbx** [comment]
@saket @luis-cortes what's the suggested workaround here?  IntrinsticMax or something?

**Comment by saket** [comment]
Sorry I'm just seeing this. I'm actually not sure what's the right way to go about this. I tried running @mattinger's code but I'm seeing a different `java.lang.OutOfMemoryError: Java heap space` error. Something about this combination of `Scaffold` + `RenderingMode.V_SCROLL` is resulting in layoutlib trying to allocate a screen height of `Int.MAX_VALUE`.

**Comment by gamepro65** [comment]
When using V_SCROLL / H_SCROLL / FULL_EXPAND renderingModes Layoutlib measures UNSPECIFIED so the children can layout however large they like. The issue is Compose passes Constraint's size (min/max width/height) as a packed Long https://developer.android.com/reference/kotlin/androidx/compose/ui/unit/Constraints which means a width / height value cannot be larger than 16 bits (among other constraints). You'll run into this same type of issue if trying to use Lazy* components with those rendering modes. 

Other than wrapping the Scaffold in a Box with some better constraints ie. `Box(modifier = Modifier.heightIn(max = 5000.dp))`, you could also wrap a ComposeView in a View which overrides `onMeasure` and converts UNSPECIFIED to measure AT_MOST with a max size of 16 bits
```
  override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
    val widthSpec = if (MeasureSpec.getMode(widthMeasureSpec) == MeasureSpec.UNSPECIFIED) {
      MeasureSpec.makeMeasureSpec(0xFFFF, MeasureSpec.AT_MOST)
    } else {
      widthMeasureSpec
    }

    val heightSpec = if (MeasureSpec.getMode(heightMeasureSpec) == MeasureSpec.UNSPECIFIED) {
      MeasureSpec.makeMeasureSpec(0xFFFF, MeasureSpec.AT_MOST)
    } else {
      heightMeasureSpec
    }

    super.onMeasure(widthSpec, heightSpec)
  }
```

Just be careful how large you go else you'll run into what @saket mentioned with respect to running out of heap space trying to take too large of a snapshot.

**Comment by jrodbx** [comment]
Closing, per @gamepro65 's accepted response.
