### ISSUE TITLE
recordPaparazzi task sometime fails with java.io.FileNotFoundException: (File name too long)

### ISSUE THREAD

**Issue by martirius** [cashapp/paparazzi#734]
**Description**
Trying to run tests with `TestParameterInjector` runner sometime fails because the name generated from paparazzi is too long.

To mitigate the problem, I had to rename some test using `@JvmName`, but i don't like it; moreover some tests will continue to fail.

This is the stacktrace
```
java.io.FileNotFoundException: src/test/snapshots/images/com.redacted.redacted.ui.realtime.screenshots_RealtimeScreenshotTest_rds[isExpanded=false,ar,com.redacted.redacted.model.WatchdogDeviceState$MissingBluetoothPermissions@21a21c64]_realtime_missingbluetoothpermissions_close_connected_updated_active_none_low_risk__ar.png (File name too long)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:236)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.cash.paparazzi.HtmlReportWriter$newFrameHandler$1.close(HtmlReportWriter.kt:105)
	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:56)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:270)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:200)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:199)
	at com.redacted.redacted.ui.ScreenshotRule.takeScreenshotLocalized(ScreenshotRule.kt:33)
	at com.redacted.redacted.ui.realtime.screenshots.RealtimeScreenshotTest.realtimeTest(RealtimeScreenshotTest.kt:207)
	at com.redacted.redacted.ui.realtime.screenshots.RealtimeScreenshotTest.realtimeTest$default(RealtimeScreenshotTest.kt:196)
	at com.redacted.redacted.ui.realtime.screenshots.RealtimeScreenshotTest.rds(RealtimeScreenshotTest.kt:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.google.testing.junit.testparameterinjector.PluggableTestRunner$2.evaluate(PluggableTestRunner.java:248)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:118)
	at com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:429)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

The real name passed to `paparazzi.snapshot` is this, `realtime_missingbluetoothpermissions_close_connected_updated_active_none_low_risk__ar`; all the rest was added

**Steps to Reproduce**
Run test with TestParameterInjector where with different  `@TestParameter` and where one  is a sealed class, and its subclasses have a few parameters in constructor.

**Expected behavior**
Test shouldn't fail and a nice to have would be be having the name passed in the method as parameter.

**Additional information:**
    Paparazzi Version: 1.2.0
    OS: MacOS Ventura 13.2.1
    Compile SDK: 33
    Gradle Version: 7.5.1
    Android Gradle Plugin Version: 7.3.1

**Comment by TWiStErRob** [comment]
You're using parameterized tests, so it's not just Paparazzi adding the name, it's scoping the `snapshot()` call to the test that called it. You can call `snapshot("same-thing")` in every test, and they won't overwrite each other.

The name generation is here:
https://github.com/cashapp/paparazzi/blob/a76702744a7f380480f323ffda124e845f2733aa/paparazzi/paparazzi/src/main/java/app/cash/paparazzi/Snapshot.kt#L35-L40

Try to shorten the TPI name by using one of these:
https://github.com/google/TestParameterInjector#use-a-test-enum-for-enumerating-more-complex-parameter-combinations
(The whole second half the README is about naming tests in different ways.)

**Comment by martirius** [comment]
Thanks for the tip, I used enumeration and that fixed!
Closing.
