### ISSUE TITLE
Render mode SHRINK does not work correctly with AlertDialog composable

### ISSUE THREAD

**Issue by Th0MmyS** [cashapp/paparazzi#769]
Preview in AS:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/11424077/236393958-52782807-ff78-4f39-8b71-f9d6d657dcb3.png">

Code:
```
@Composable
fun ComposeDialog(
	modifier: Modifier = Modifier,
	title: String,
	subtitle: String,
	openDialogState: MutableState<Boolean> = remember { mutableStateOf(false) },
	isCancelable: Boolean = true,
	onDismissRequest: () -> Unit = {
		if (isCancelable) {
			openDialogState.value = false
		}
	},
) {
	AlertDialog(
		modifier = modifier
			.fillMaxWidth()
			.clip(RoundedCornerShape(12.dp)),
		onDismissRequest = onDismissRequest,
		title = {
			Text(
				modifier = Modifier
					.fillMaxWidth(),
				textAlign = TextAlign.Center,
				text = title
			)
		},
		text = {
			Text(
				modifier = Modifier
					.fillMaxWidth(),
				textAlign = TextAlign.Center,
				text = subtitle
			)
		},
		buttons = {
			Column(
				modifier = Modifier
					.fillMaxWidth()
					.padding(
						start = 16.dp,
						end = 16.dp,
						bottom = 16.dp
					)
			) {
				Button(
					modifier = Modifier.fillMaxWidth(),
					onClick = {},
					) {
					Text("test")
				}
				Spacer(modifier = Modifier.height(16.dp))
				Button(
					modifier = Modifier.fillMaxWidth(),
					onClick = {},
				) {
					Text("test")
				}
			}
		}
	)
}

@Preview
@Composable
fun ComposeDialogPreview() {
	ComposeDialog(
		title = "Title",
		subtitle = "Subtitle"
	)
}
```

Paparazzi config:
```
@get:Rule
	val paparazzi = Paparazzi(
		maxPercentDifference = 1.0,
		deviceConfig = DeviceConfig.PIXEL_5.copy(softButtons = false),
		renderingMode = SessionParams.RenderingMode.SHRINK
	)
```

Stacktrace:

```java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:524)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:456)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:307)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:306)
	at app.cash.paparazzi.Paparazzi.withTime(Paparazzi.kt:348)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:306)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:200)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:199)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:195)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:191)
	at cz.cleevio.screenshot.ComposePaparazziTests.preview_tests(ScreenShotUnitTest.kt:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.google.testing.junit.testparameterinjector.PluggableTestRunner$3.evaluate(PluggableTestRunner.java:273)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:118)
	at com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:420)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by jrodbx** [comment]
Fixed in https://github.com/cashapp/paparazzi/pull/969.
