### ISSUE TITLE
Paparazzi tests on Skiko

### ISSUE THREAD

**Issue by hbrtose** [cashapp/paparazzi#981]
I am using Paparazzi to test an Android App using Skiko (Skia for Kotlin Multiplattform), it has separate runtimes for different platforms and when I'm trying to run tests for my app on a Windows machine it demands a Skiko windows runtime instaed of Android runtime provided. I'm getting a `java.lang.ExceptionInInitializerError` with following message.

```Caused by:
        org.jetbrains.skiko.LibraryLoadException: Cannot find skiko-windows-x64.dll.sha256, proper native dependency missing.
            at app//org.jetbrains.skiko.Library.findAndLoad(Library.kt:105)
            at app//org.jetbrains.skiko.Library.load(Library.kt:59)
            at app//org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
            at app//org.jetbrains.skia.paragraph.ParagraphStyle.<clinit>(ParagraphStyle.kt:17)
            ... 40 more
```

**Comment by jrodbx** [comment]
TIL Skiko.  @JakeWharton thoughts on support + any pointers/ideas on how one might consider down this path?

**Comment by TWiStErRob** [comment]
It sounds reasonable that running JVM tests on Windows needs DLLs. Paparazzi is not emulating Android, it's running Android-like source code (layoutlib) in JVM unit tests similar to Robolectric.

What happens if you add the windows runtime as a dependency for `testRuntimeOnly`?

If that works, then it's possible to [patch](https://docs.gradle.org/current/userguide/resolution_rules.html) with arbitrary logic from a plugin.
<details><summary>something like</summary>

```gradle
configurations.debugUnitTestRuntimeClasspath.resolutionStrategy.eachDependency {
    if (requested.group == "org.jetbrains.skiko" && requested.name == "skiko-android-runtime-x64") {
            val jvmTarget = "windows-x64" // This can be calculated as per skiko README.
            useTarget("org.jetbrains.skiko:skiko-jvm-runtime-${jvmTarget}:${requested.version}")
            because("Targeting JVM that's running this Gradle build and therefore unit tests.")
    }
}
```

Ideally this selection would be driven by Gradle variants, capabilities and attributes, but skiko doesn't publish Gradle metadata for all its modules. It's possible to [build it externally](https://github.com/gradlex-org/java-ecosystem-capabilities) too.

</details>

**Comment by hbrtose** [comment]
The issue when adding windows dependency for test only is that some of the code required of embeding Skiko object in and Android view is platform specific, so in my case

```
val holder = FrameLayout(it)
val skiaLayer = SkiaLayer().apply {
            gesturesToListen = SkikoGestureEventKind.values()
}
val skikoCube= SkikoCube(skiaLayer)
skiaLayer.skikoView = GenericSkikoView(skiaLayer, skikoCube)
skiaLayer.attachTo(holder)
```

does not work on windows runtime, because Windows version of SkiaLayer, because it has different constructor arguments

**Comment by JakeWharton** [comment]
You'll have to use something like an interface with multiple implementations that you choose based on the JVM's host OS. I don't see anything here for paparazzi to be involved in.
